import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("AI 工具调用记录界面", () => {
  it("生成时展开思考与工具步骤并在最终答案出现后折叠", async () => {
    const publicPath = join(process.cwd(), "src", "public");
    const [page, application, styles] = await Promise.all([
      readFile(join(publicPath, "index.html"), "utf8"),
      readFile(join(publicPath, "app.js"), "utf8"),
      readFile(join(publicPath, "styles.css"), "utf8")
    ]);

    expect(page).toContain('id="ai-tool-call-dialog"');
    expect(page).toContain('id="ai-tool-call-name"');
    expect(page).toContain('id="ai-tool-call-time"');
    expect(page).toContain('id="ai-tool-call-description"');
    expect(page).toContain('<dt>返回字符数</dt><dd id="ai-tool-call-result-length"></dd>');
    expect(page).toContain('id="ai-tool-call-arguments"');
    expect(page).toContain('id="ai-tool-call-result"');
    expect(page).toContain('data-copy-target="ai-tool-call-arguments"');
    expect(page).toContain('data-copy-target="ai-tool-call-result"');
    expect(page).toContain('class="ai-tool-call-copy-button"');
    expect(application).toContain('eventName === "tool_call"');
    expect(application).toContain('eventName === "process_step"');
    expect(application).toContain('`调用了 ${name} 工具`');
    expect(application).toContain("function renderAiProcessSteps(message, steps, completed, durationMs = null, visibleContents = null)");
    expect(application).toContain("const previousScrollStates = new Map();");
    expect(application).toContain("section.dataset.aiProcessStepId");
    expect(application).toContain("body.scrollTop = scrollState.nearBottom");
    expect(application).toContain("function scrollAiProcessStepsToBottom(message)");
    expect(application).toContain("if (!completed) scrollAiProcessStepsToBottom(message);");
    expect(application).toContain("function shouldRenderAiProcessStep(step)");
    expect(application).toContain('step.type !== "intermediate" || typeof step.content !== "string" || step.content.trim().length > 0');
    expect(application).toContain("const renderableSteps = (Array.isArray(steps) ? steps : []).filter(shouldRenderAiProcessStep);");
    expect(application).toContain("if (!renderableSteps.length) return;");
    expect(application).toContain("const aiFeedAutoScrollStates = new WeakMap();");
    expect(application).toContain("const aiFeedScrollBindings = new WeakSet();");
    expect(application).toContain("function aiFeedIsNearBottom(feed)");
    expect(application).toContain("function bindAiFeedAutoScroll(feed)");
    expect(application).toContain('feed.addEventListener("scroll", update, { passive: true });');
    expect(application).toContain("if (!aiFeedAutoScrollStates.get(feed)) return;");
    expect(application).toContain("window.cancelAnimationFrame(currentFrame);");
    expect(application).toContain("const processStepTypewriters = new Map();");
    expect(application).toContain("processStepTypewriter(targetStep).append(step.content)");
    expect(application).toContain('step.type === "intermediate" && typeof step.content === "string"');
    expect(application).toContain("typewriter.replace(streamedText)");
    expect(application).toContain('step.type === "thinking") {');
    expect(application).toContain("const content = visibleContents?.has(step) ? visibleContents.get(step) : step.content;");
    expect(application).toContain('step?.type === "context_compaction"');
    expect(application).toContain('createAiContextCompactionDivider({');
    expect(application).toContain('kind: "tool"');
    expect(application).toContain('divider.setAttribute("role", "separator")');
    expect(application).toContain("function formatAiProcessDuration(value)");
    expect(application).toContain("function resolveAiProcessDuration(metadata, steps, completedAt)");
    expect(application).toContain('` · 耗时 ${duration}`');
    expect(application).toContain("toolCalls, processSteps, processDurationMs");
    expect(application).toContain("details.open = !completed");
    expect(application).toContain("renderStreamingProcessSteps(false, elapsedProcessTime())");
    expect(application).toContain('title.textContent = completed ? "思考与执行过程" : "正在思考与执行"');
    expect(application).toContain('function scrollAiFeedToBottom(feed = $("#ai-feed"))');
    expect(application).toContain("window.requestAnimationFrame(() =>");
    expect(application.match(/scrollAiFeedToBottom\(feed\);/gu)?.length).toBeGreaterThanOrEqual(7);
    expect(application).toContain('return "历史记录未保存"');
    expect(application).toContain('new Intl.DateTimeFormat("zh-CN"');
    expect(application).toContain('formatAiToolCallResult(toolCall?.result)');
    expect(application).toContain('`${resultDetails.characterCount.toLocaleString("zh-CN")} 字符`');
    expect(application).toContain("async function copyAiToolCallCode(button)");
    expect(application).toContain("await copyAiRawMarkdown(target.textContent)");
    expect(application).toContain("const AI_TOOL_CALL_COPIED_ICON");
    expect(application).toContain("button.innerHTML = copied ? AI_TOOL_CALL_COPIED_ICON : AI_TOOL_CALL_COPY_ICON");
    expect(application).toContain('data-ai-tool-call-copy');
    expect(styles).toContain(".ai-tool-call-summary::after { content: \"查看详情\";");
    expect(styles).toContain(".ai-process-details > summary");
    expect(styles).toContain(".ai-process-step-body");
    expect(styles).toContain("overflow-y: auto");
    expect(styles).toContain("scrollbar-gutter: stable");
    expect(styles).toContain(".ai-tool-call-detail { display: grid; grid-template-columns: minmax(0, 1fr);");
    expect(styles).toContain(".ai-tool-call-info { display: grid;");
    expect(styles).toContain(".ai-tool-call-copy-button { position: absolute;");
    expect(styles).toContain(".ai-tool-call-code-block { position: relative;");
    expect(styles).toContain("padding: 12px 44px 12px 12px;");
    expect(page).toContain("feature=ai-write-card-actions-compact-v1");
    expect(page).toContain("feature=ai-write-plan-actions-footer-v1");
    expect(styles).toContain(".ai-interactive-actions :is(button.ghost-button, button.primary-button) { min-width: 0; min-height: 24px; padding: 3px 7px; font-size: calc(9px * var(--ai-font-scale)); line-height: 1.35; }");
    expect(styles).toContain(".card-actions.ai-plan-actions { flex-wrap: wrap; justify-content: flex-end; gap: 6px; margin-top: 0; padding: 14px 24px 20px; }");
    expect(styles).not.toContain("padding: 30px 12px 12px;");
    expect(styles).not.toContain("ai-stream-cursor");
    expect(styles).not.toContain(".is-streaming .message-body:empty::after");
  });
});
