import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("AI 分析范围交互", () => {
  it("选择全书时禁用章节选项，并在切回指定章节后恢复", async () => {
    const publicPath = join(process.cwd(), "src/public");
    const [application, styles, page] = await Promise.all([
      readFile(join(publicPath, "app.js"), "utf8"),
      readFile(join(publicPath, "styles.css"), "utf8"),
      readFile(join(publicPath, "index.html"), "utf8")
    ]);

    expect(application).toContain('allSettingsOption.textContent = "全书 + 设定集"');
    expect(application).toContain('chapterSettingsOption.textContent = "指定章节 + 设定集"');
    expect(application).toContain('settingsOnlyOption.textContent = "仅设定集"');
    expect(application).toContain('["chapter-with-settings", "book-with-settings"].includes(scopeType)');
    expect(application).toContain('const settingsOnly = taskType === "relationship-analysis" && scopeType === "settings"');
    expect(application).toContain('function analysisTaskModelPurpose(taskType)');
    expect(application).toContain('name="modelId" required aria-describedby="analysis-task-model-help"');
    expect(page).toContain('class="dialog-close" value="cancel" aria-label="关闭" type="submit" formnovalidate');
    expect(page).toContain('class="ghost-button" value="cancel" type="submit" formnovalidate>取消</button>');
    expect(application).toContain('默认值来自“本书 AI 设置”，只修改当前任务，不会改变全书默认模型。');
    expect(application).toContain('const defaultId = defaultModelByTask.get(analysisTaskModelPurpose(taskTypeSelect.value)) ?? ""');
    expect(application).toContain('body: { taskType, scope, modelId }');
    expect(application).toContain('body: {}');
    expect(application).toContain('{ type: "settings"');
    expect(application).toContain('const enabled = taskTypeSelect.value === "relationship-analysis"');
    expect(application).toContain('[["chapter", "指定章节"], ["book", "全书"]]');
    expect(application).toContain('data-task-scope-volume-input');
    expect(application).toContain('data-task-scope-volume-toggle');
    expect(application).toContain('setTaskScopeVolumeCollapsed');
    expect(application).toContain('for (const collapseButton of scopeVolumeCollapseButtons)');
    expect(application).toContain('勾选以全选本卷章节');
    expect(application).not.toContain('data-task-scope-field="volume"');
    expect(application).toContain('const chapterIds = form.getAll("chapterIds").map(String).filter(Boolean)');
    expect(application).toContain('const scopeVolumeInputs = [');
    expect(application).toContain('syncTaskScopeVolumeInputs');
    expect(application).toContain('for (const volumeInput of scopeVolumeInputs) volumeInput.addEventListener("change"');
    expect(application).toContain('body: { taskType, scope, modelId }');
    expect(application).not.toContain('/tasks/context-preview');
    expect(application).toContain('data-analysis-context-warning');
    expect(application).toContain('上下文更长的模型');
    expect(application).toContain('error.code === "AI_CONTEXT_TOO_LARGE"');
    expect(application).not.toContain('taskType === "character-identity-audit" || scopeType === "book"');
    expect(application).toContain('const enabled = ["chapter", "chapter-with-settings"].includes(scopeTypeSelect.value)');
    expect(application).toContain('bookScopeOption.before(chapterSettingsOption)');
    expect(application).toContain('scopeFields[kind].setAttribute("aria-disabled", String(!enabled))');
    expect(application).toContain('scopeTriggers[kind].disabled = !enabled');
    expect(application).toContain('data-task-scope-search');
    expect(application).toContain('data-task-scope-clear');
    expect(application).toContain('data-task-scope-selected-list');
    expect(application).toContain('data-task-scope-remove');
    expect(application).toContain('class="task-scope-author-note-banner" role="note"');
    expect(application).toContain('标记为“作者的话”的章节不会纳入 AI 分析输入');
    expect(application).toContain('标记为“作者的话”的章节除外');
    expect(application).toContain('scopeSelectedLists[kind].addEventListener');
    expect(application).toContain('scopeBubbles[kind].scrollIntoView({ block: "start" })');
    expect(application).toContain('scopeTypeSelect.addEventListener("change", () =>');
    expect(application).toContain('name="additionalPrompt" maxlength="10000"');
    expect(application).toContain('class="relationship-character-trigger"');
    expect(application).toContain('data-relationship-character-search');
    expect(application).toContain('data-relationship-character-clear');
    expect(application).toContain('input[name="characterIds"]');
    expect(application).toContain('class="relationship-analysis-helper"');
    expect(application).toContain('name="preFilterRelationshipSources" type="checkbox" checked disabled');
    expect(application).toContain("无差别发送所选范围内的全部章节和设定来源");
    expect(application).toContain('form.get("preFilterRelationshipSources") === "on"');
    expect(application).toContain("preFilterRelationships.disabled = !hasSelectedCharacters");
    expect(application).toContain("发送来源预检");
    expect(application).toContain("/tasks/relationship-source-preview");
    expect(application).toContain("scope.relationshipSourceRefs");
    expect(application).toContain("data-relationship-source-selected");
    expect(application).toContain("renderRelationshipSourcePreview");
    expect(application).toContain("invalidateRelationshipSourcePreview");
    expect(application).toContain("默认仅追加不存在的关系，不修改或删除已有关系");
    expect(application).toContain("不勾选则只追加新关系");
    expect(application).toContain('class="relationship-overwrite-card relationship-existing-overwrite-card hidden"');
    expect(application).toContain('name="replaceExistingRelationships" type="checkbox" disabled');
    expect(application).toContain('relationshipOptions.classList.toggle("hidden", !enabled)');
    expect(application).toContain("relationshipCharacterInputs.some((input) => input.checked)");
    expect(application).toContain("replaceRelationships.disabled = !hasSelectedCharacters");
    expect(application).toContain('relationshipOverwriteCard.classList.toggle("hidden", !hasSelectedCharacters)');
    expect(application).toContain('relationshipCharacterTrigger.addEventListener("click"');
    expect(application).toContain('relationshipCharacterSearch.addEventListener("input", filterRelationshipCharacters)');
    expect(application).toContain('setRelationshipCharacterBubbleOpen(false)');
    expect(application).toContain("includeAllSettings: true");
    expect(application).toContain('form.setAttribute("aria-busy", "true")');
    expect(application).toContain("if (submitting)");
    expect(application).toContain("control.disabled = true");
    expect(application).toContain("dialog.oncancel");
    expect(application).toContain('pendingLabel: "创建中…"');
    expect(application).toContain('pendingMessage: "正在创建分析任务，请稍候"');
    expect(application).toContain('errorPrefix: "任务创建失败："');
    expect(application).toContain('toast("分析任务已创建，已进入任务队列");\n    await refreshAnalysisTaskViewsAfterCreate(workId)');
    expect(application).toContain('async function refreshAnalysisTaskViewsAfterCreate(workId)');
    expect(application).toContain('renderTasks(1, { refresh: true })');
    expect(application).toContain('toast(`任务已创建，但列表刷新失败：${error.message}`, "error")');
    expect(page).toContain('feature=analysis-task-queue-refresh-v1');
    expect(page).toContain('id="dialog-submit-status"');
    expect(page).toContain('class="dialog-submit-progress" role="progressbar"');
    expect(styles).toContain(".task-chapter-field.is-disabled { opacity: .48; }");
    expect(styles).toContain(".task-chapter-field select:disabled { cursor: not-allowed; }");
    expect(styles).toContain(".task-scope-picker { display: grid; gap: 8px; min-width: 0; }");
    expect(styles).toContain(".task-scope-options { display: grid; align-content: start; gap: 6px;");
    expect(styles).toContain(".task-scope-volume-options { display: grid; gap: 5px;");
    expect(styles).toContain(".task-scope-volume-group.is-collapsed > .task-scope-volume-options { display: none; }");
    expect(styles).toContain(".task-scope-volume-collapse { display: inline-grid;");
    expect(styles).toContain(".task-scope-panel-grid { display: grid;");
    expect(styles).toContain(".task-scope-selected-list { display: grid;");
    expect(styles).toContain(".task-scope-checkbox { display: inline-grid; width: 18px; height: 18px; place-items: center; border: 1px solid var(--line);");
    expect(styles).toContain(".task-scope-author-note-banner {");
    expect(styles).toContain(".dialog-fields .task-scope-search input { min-height: 34px;");
    expect(styles).toContain(".relationship-character-bubble {");
    expect(styles).toContain(".relationship-character-options {");
    expect(styles).toContain(".relationship-analysis-helper {");
    expect(styles).toContain(".relationship-overwrite-card {");
    expect(styles).toContain(".relationship-source-preview-card {");
    expect(styles).toContain(".relationship-source-preview-row {");
    expect(styles).toContain(".analysis-context-warning {");
    expect(styles).toContain(".dialog-submit-status {");
    expect(styles).toContain("@keyframes dialog-submit-progress");
  });
});
