import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { once } from "node:events";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Runtime } from "../../src/app.js";
import { createRuntime } from "../../src/app.js";

describe("作者完整创作流程", () => {
  let runtime: Runtime;
  let mockServer: ReturnType<typeof createServer>;
  let baseUrl: string;
  const receivedBodies: Array<Record<string, unknown>> = [];

  beforeAll(async () => {
    mockServer = createServer(async (incoming: IncomingMessage, outgoing: ServerResponse) => {
      if (incoming.url === "/v1/models") {
        outgoing.writeHead(200, { "Content-Type": "application/json" });
        outgoing.end(JSON.stringify({ data: [{ id: "system-novel-model" }] }));
        return;
      }
      if (incoming.url === "/v1/chat/completions" && incoming.method === "POST") {
        const chunks: Buffer[] = [];
        for await (const chunk of incoming) chunks.push(Buffer.from(chunk));
        const body = JSON.parse(Buffer.concat(chunks).toString("utf8")) as Record<string, unknown>;
        receivedBodies.push(body);
        const messages = body.messages as Array<{ content: string }>;
        const prompt = messages.map((message) => message.content ?? "").join("\n");
        let content = "舱门关闭，林舟望向逐渐远去的北港。";
        if (prompt.includes("检查下面的续写候选")) {
          content = "[]";
        } else if (prompt.includes("抽取大事件候选")) {
          content = JSON.stringify([{ name: "北港启航", description: "林舟驾驶飞船离开北港。", eventType: "离别", timeLabel: "启航日", timeSort: 1, location: "北港", impactScope: "personal", chapterIds: [], participantIds: [], evidence: [{ quote: "飞船驶离北港" }] }]);
        } else if (prompt.includes("小说人物关系抽取器")) {
          const chapters = [...prompt.matchAll(/<CHAPTER id="([^"]+)" title="([^"]+)">/gu)];
          content = JSON.stringify([{ fromCharacterId: "林舟", toCharacterId: "沈星", category: "social", subtype: "朋友", directed: false, currentStatus: "active", timeRange: { start: "第一卷" }, confidence: 0.82, evidence: chapters.map((match, index) => ({ chapterId: match[1], chapterTitle: match[2], quote: index === 0 ? "林舟想起沈星的警告" : "沈星仍保存着林舟的旧信", contextType: "current", supports: "两人保持长期联系" })) }]);
        }
        if (body.stream === true) {
          outgoing.writeHead(200, { "Content-Type": "text/event-stream" });
          outgoing.write(`data: ${JSON.stringify({ choices: [{ delta: { content: "舱门关闭，" } }] })}\n\n`);
          await new Promise((resolve) => setTimeout(resolve, 8));
          outgoing.write(`data: ${JSON.stringify({ choices: [{ delta: { content: "飞船离开北港。" }, finish_reason: "stop" }] })}\n\n`);
          outgoing.end("data: [DONE]\n\n");
          return;
        }
        outgoing.writeHead(200, { "Content-Type": "application/json" });
        outgoing.end(JSON.stringify({ choices: [{ message: { content } }] }));
        return;
      }
      outgoing.writeHead(404).end();
    });
    mockServer.listen(0, "127.0.0.1");
    await once(mockServer, "listening");
    const address = mockServer.address();
    if (!address || typeof address === "string") throw new Error("Mock server failed to start");
    baseUrl = `http://127.0.0.1:${address.port}/v1`;
    runtime = createRuntime({
      databasePath: ":memory:",
      masterSecret: "system-test-master-secret-with-enough-length",
      disableUserAuth: true,
      serveUi: true
    });
  });

  afterAll(async () => {
    await runtime.close();
    mockServer.close();
    await once(mockServer, "close");
  });

  it("章节概览使用 Toast 且正文编辑区始终占满剩余高度", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    const chapterVirtualization = await request(runtime.app).get("/chapter-editor-virtualization.js").expect(200);
    expect(page.text).toContain('<div class="editor-body">');
    expect(page.text).not.toContain('id="chapter-insight"');
    expect(page.text).toContain('id="insight-button" class="ghost-button" type="button" aria-controls="chapter-insight-toast" aria-expanded="false"');
    expect(page.text).toContain('id="chapter-line-numbers"');
    expect(page.text).not.toContain('id="toggle-whitespace-button"');
    expect(page.text).toContain('id="chapter-whitespace-overlay"');
    expect(page.text).toContain('id="new-volume-button" class="add-button"');
    expect(page.text).not.toContain('id="new-chapter-button"');
    expect(application.text).toContain("选择第 ${index + 1} 行");
    expect(page.text).toContain('id="left-panel-resize"');
    expect(page.text).toContain('id="ai-panel-resize"');
    expect(page.text).toContain('<div class="panel-heading">');
    expect(page.text).toContain('<div class="ai-heading">');
    expect(page.text).toContain('<div class="ai-heading-actions">');
    expect(page.text).toContain('aria-label="新建对话" title="新建对话">＋</button>');
    expect(page.text).not.toContain('class="ai-conversation-toolbar"');
    expect(styles.text).toContain(".quick-actions { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));");
    expect(styles.text).toContain(".editor-view { container-name: editor-workspace; container-type: inline-size; display: grid; grid-template-rows: auto auto minmax(0, 1fr); height: 100%; }");
    expect(styles.text).toContain("@container editor-workspace (max-width: 720px)");
    expect(styles.text).toContain(".chapter-stats { display: none; }");
    expect(styles.text).toContain(".editor-body { display: flex; grid-row: 3; min-height: 0; flex-direction: column; }");
    expect(styles.text).toContain(".chapter-editor-frame { position: relative; display: grid;");
    expect(styles.text).toContain(".user-message { width: fit-content; max-width: 60%; margin-left: auto;");
    expect(styles.text).toContain(".ai-prompt { display: block; width: 100%; min-height: 104px; margin: 0;");
    expect(styles.text).toContain(".ai-feed { flex: 1; min-height: 0; overflow-y: auto;");
    expect(application.text).toContain("function renderChapterLineNumbers({ targetLineIndex = null } = {})");
    expect(application.text).toContain("syncChapterLineNumberScroll");
    expect(application.text).toContain("function renderChapterWhitespaceMarkers(input, style, layout, lineWindow, getLineBounds, totalHeight)");
    expect(application.text).toContain('/chapter-editor-virtualization.js?v=20260810-visible-lines-v1');
    expect(application.text).toContain("scheduleChapterLineNumbers(chapterLineInputRenderDelay)");
    expect(application.text).toContain("inner.dataset.renderedLineCount");
    expect(chapterVirtualization.text).toContain("export function buildChapterLineMirror(value)");
    expect(chapterVirtualization.text).toContain("export function findChapterLineWindow(lineCount, getBounds, viewportStart, viewportEnd)");
    expect(application.text).toContain('element.className = "toast chapter-insight-toast"');
    expect(application.text).toContain('element.id = "chapter-insight-toast"');
    expect(application.text).toContain('chapterName.className = "chapter-insight-toast-chapter-title"');
    expect(application.text).toContain('chapterName.textContent = chapterTitle');
    expect(application.text).toContain("function dismissChapterInsightToast()");
    expect(styles.text).toContain(".chapter-insight-toast {");
    expect(styles.text).toContain(".chapter-insight-toast-heading .chapter-insight-toast-chapter-title");
    expect(application.text).toContain('data-toggle-whitespace');
    expect(application.text).toContain('document.querySelectorAll("[data-toggle-whitespace]")');
    expect(page.text).toContain('id="toggle-whitespace-appearance"');
    expect(application.text).toContain("function toggleChapterWhitespaceVisibility()");
    expect(application.text).toContain('/whitespace-visualization.js?v=20260718-visible-whitespace');
    expect(application.text).toContain("function setupPanelResize(handle, side)");
    expect(application.text).toContain("function ensureAiPanelExpanded()");
    expect(styles.text).toContain(".app-shell.left-panel-collapsed");
    expect(styles.text).toContain(".app-shell.left-panel-collapsed .panel-heading");
    expect(styles.text).toContain(".app-shell.ai-panel-collapsed .ai-heading");
    expect(application.text).toContain("function addSelectedLinesAsCitation()");
    expect(application.text).toContain("input.setSelectionRange(selection.startOffset, selection.startOffset)");
    expect(application.text).toContain('addEventListener("contextmenu"');
    expect(application.text).toContain("state.aiCitations.map");
    expect(application.text).toContain('addEventListener("pointermove"');
    expect(styles.text).toContain(".chapter-line-number.is-line-selected");
    expect(styles.text).toContain(".chapter-line-number.is-line-selected::after");
    expect(styles.text).toContain(".app-shell:not(.shelf-mode):not(.ai-workspace-mode) { grid-template-columns: minmax(0, 1fr); }");
    expect(styles.text).toContain(".chapter-space-marker::after");
    expect(styles.text).toContain(".chapter-space-marker.tab::after");
    expect(styles.text).toContain("width: 100vw; height: 100%");
    expect(styles.text).toContain("grid-template-columns: 38px minmax(0, 1fr)");
    expect(styles.text).toContain("width: 100%; min-height: 0; margin: 0;");
    expect(styles.text).toContain("font-variant-numeric: tabular-nums; text-align: center");
    expect(styles.text).toContain("font-size: clamp(11px, calc(var(--editor-font-size) * .72), 14px); line-height: 1.2");
    expect(styles.text).toContain("align-items: flex-start; justify-content: center");
    expect(styles.text).toContain("grid-template-columns: minmax(0, 1fr) max-content");
    expect(styles.text).toContain("overflow-wrap: anywhere; line-height: 1.45; white-space: normal");
    expect(page.text).toContain('id="ai-citations"');
    expect(page.text).toContain('id="line-citation-menu"');
    expect(page.text).toContain('<button id="chapter-delete-button" class="danger-button" type="button">删除章节</button>');
    expect(page.text).toContain('data-delete-chapter');
    expect(application.text).toContain("async function deleteChapter(chapterId)");
    expect(application.text).toContain('title: "删除章节"');
    expect(application.text).toContain('title: "删除操作需要再次确认"');
    expect(application.text).toContain('method: "DELETE", body: { expectedVersionNo }');
  });

  it("作品切换和新建只保留在书架首页", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    expect(page.text).not.toContain('id="work-picker"');
    expect(page.text).not.toContain('id="new-work-button"');
    expect(page.text).toContain('id="shelf-new-work"');
    expect(application.text).toContain('id="book-add-card"');
    expect(application.text).not.toContain('$("#work-picker")');
  });

  it("登录成功后丢弃原作品路由并只进入书架", async () => {
    const application = await request(runtime.app).get("/app.js").expect(200);
    expect(application.text).toContain('window.history.replaceState(null, "", serializePageRoute({ view: "shelf" }));\n    window.location.reload();');
  });

  it("全站使用黑体与等宽英文并提供可持久化显示和明暗主题", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    const theme = await request(runtime.app).get("/theme.js").expect(200);
    await request(runtime.app).get("/theme-init.js").expect(200);
    expect(page.text).toContain('id="appearance-button"');
    expect(page.text).toContain('id="appearance-dialog"');
    expect(page.text).toContain('id="theme-toggle"');
    expect(page.text).toContain('theme-icon-moon');
    expect(page.text).toContain('theme-icon-sun');
    expect(page.text).toContain("英文字体（仅等宽）");
    expect(styles.text).toContain('--font-cjk: "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", "Heiti SC";');
    expect(styles.text).toContain('--font-latin: "SFMono-Regular", "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono";');
    expect(styles.text).toContain("--editor-line-height: 1.55;");
    expect(styles.text.replaceAll("sans-serif", "").toLowerCase()).not.toContain("serif");
    expect(application.text).toContain('const typographyStorageKey = "ai-novel-typography-v1";');
    expect(application.text).toContain("localStorage.setItem(typographyStorageKey");
    expect(styles.text).toContain(':root[data-theme="dark"]');
    expect(theme.text).toContain('THEME_STORAGE_KEY = "scriverse-color-theme-v1"');
  });

  it("首次登录展示指向真实控件的聚光灯导览", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    expect(page.text).toContain('id="onboarding-dialog"');
    expect(page.text).toContain('data-testid="first-use-onboarding"');
    expect(page.text).toContain('id="onboarding-menu-button"');
    expect(page.text).toContain('id="onboarding-spotlight"');
    expect(page.text).toContain('id="onboarding-popover"');
    expect(page.text).not.toContain("data-onboarding-step");
    expect(application.text).toContain("const shelfOnboardingSteps = [");
    expect(application.text).toContain("const workspaceOnboardingSteps = [");
    expect(application.text).toContain("function positionOnboardingElements()");
    expect(application.text).toContain('selector: "[data-new-chapter-volume]"');
    expect(application.text).toContain('selector: ".quick-actions button[data-task=\\"continue\\"]"');
    expect(application.text).toContain("function scheduleFirstUseOnboarding()");
    expect(application.text).toContain('api("/api/auth/onboarding/complete", { method: "POST", body: {} })');
    expect(application.text).toContain('addEventListener("cancel"');
    expect(application.text).toContain('event.key === "Escape"');
    expect(styles.text).toContain(".onboarding-dialog {");
    expect(styles.text).toContain(".onboarding-spotlight {");
    expect(styles.text).toContain("0 0 0 9999px rgba(20,18,16,.7)");
    expect(styles.text).toContain('.onboarding-popover[data-placement="right"]::before');
  });

  it("复杂人物使用分区编辑器并提供版本历史与回滚入口", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    await request(runtime.app).get("/character-version.js").expect(200);
    expect(page.text).toContain('id="entity-editor-view"');
    expect(page.text).toContain('id="setting-editor-form"');
    expect(page.text).toContain('id="character-editor-form"');
    expect(page.text).toContain('id="knowledge-editor-form"');
    expect(page.text).toContain('id="character-history-button"');
    expect(page.text).not.toContain('id="setting-editor-management"');
    expect(page.text).toContain('<button id="setting-editor-history" class="ghost-button hidden" type="button">版本历史</button>');
    expect(page.text).toContain('<button id="setting-editor-delete" class="danger-button hidden" type="button">删除设定</button>');
    expect(page.text).toContain('id="character-merge-button"');
    expect(page.text).toContain('id="character-delete-button"');
    expect(page.text.match(/data-character-editor-tab=/gu)).toHaveLength(5);
    expect(page.text).toContain('data-character-editor-tab="relationships"');
    expect(page.text).toContain("简介、人设摘要、身份与动机");
    expect(page.text).toContain("保存新版本");
    expect(application.text).toContain("function renderCharacterEditorFields(item)");
    expect(application.text).toContain('field("code", "编号", "text", item?.code)');
    expect(application.text).toContain('name="personaSummary"');
    expect(application.text).toContain("人设摘要");
    expect(application.text).toContain('class="character-code"><b>编号</b>');
    expect(application.text).toContain("function openSettingEditor(item = null, { readOnly = false } = {})");
    expect(application.text).toContain("function openCharacterEditor(item = null, { readOnly = false } = {})");
    expect(application.text).toContain("function renderKnowledgeEditorFields(kind, item, memberOptions, parentOptions)");
    expect(application.text).toContain("async function openKnowledgeEditor(kind, item, { readOnly = false } = {})");
    expect(application.text.match(/if \(!\(await closeEntityEditor\(\)\)\) return;/gu)).toHaveLength(2);
    expect(application.text).toContain("async function openOrganizationDialog(item, options)");
    expect(application.text).toContain("function renderCharacterEditorRelationships()");
    expect(application.text).toContain('class="character-aliases"><b>别名</b>');
    expect(application.text).toContain('class="character-species"');
    expect(application.text).toContain("refreshRelationshipSurfaces");
    expect(application.text).toContain("data-character-relationship-edit");
    expect(application.text).toContain("data-character-relationship-delete");
    expect(application.text).toContain("sortCharacterRelationships");
    expect(application.text).toContain("async function deleteRelationshipRecord(item, characterId = null)");
    expect(application.text).toContain('const canEditRelationships = canEditModule("relationships");');
    expect(application.text).toContain('canEditRelationships ? `<button data-edit-relationship=');
    expect(application.text).toContain("data-dialog-relationship-delete");
    expect(application.text).toContain('item && canEditModule("relationships") ? `<section class="entity-dialog-management"');
    expect(application.text).toContain('title: "删除人物关系", confirmLabel: "继续删除"');
    expect(application.text).toContain('title: "删除操作需要再次确认", confirmLabel: "确认删除"');
    expect(application.text).toContain('return reopenDialog()');
    expect(application.text).toContain('method: "DELETE", body: { expectedVersionNo: item.versionNo }');
    expect(application.text).toContain('field("keywords", "关系关键词", "keyword-chips"');
    expect(application.text).toContain("splitRelationshipKeywordInput");
    expect(application.text).toContain('form.getAll("keywords")');
    expect(application.text).toContain("function renderCharacterHistory()");
    expect(application.text).toContain("/versions`");
    expect(application.text).toContain("/restore`");
    expect(application.text).toContain("buildCharacterState(form.getAll");
    expect(application.text).toContain("function openEntityMergeDialog(");
    expect(application.text).toContain("function recordCardEditButton(");
    expect(application.text).toContain("function recordHistoryButton(");
    expect(application.text).toContain('recordHistoryButton("setting", item.id, item.title)');
    expect(application.text).toContain('recordHistoryButton("race", item.id, item.name)');
    expect(application.text).toContain('recordHistoryButton("organization", item.id, item.name)');
    expect(application.text).toContain("function entityDialogManagementHtml(");
    expect(application.text).toContain("data-dialog-entity-merge");
    expect(application.text).toContain("data-dialog-entity-delete");
    expect(application.text).toContain("danger-confirm-field");
    expect(application.text).not.toContain("data-merge-character");
    expect(application.text).not.toContain("data-delete-character");
    expect(application.text).not.toContain("data-merge-race");
    expect(application.text).not.toContain("data-delete-race");
    expect(application.text).not.toContain("data-merge-organization");
    expect(application.text).not.toContain("data-delete-organization");
    expect(application.text).toContain("/merge`");
    expect(styles.text).toContain(".character-editor-workspace");
    expect(styles.text).toContain(".entity-editor-view");
    expect(styles.text).toContain("#setting-editor-form { display: grid; grid-template-rows: auto minmax(0, 1fr);");
    expect(styles.text).toContain(".setting-editor-workspace { display: grid; grid-template-rows: minmax(0, 1fr); min-height: 0; overflow: hidden; }");
    expect(styles.text).toContain(".setting-editor-content { height: auto; min-height: 70dvh; padding: 16px; }");
    expect(styles.text).toContain(".character-markdown-editor > .vditor-editor-host { width: 100%; justify-self: stretch; }");
    expect(styles.text).toContain(".knowledge-markdown-editor { grid-template-rows: minmax(0, 1fr) auto; }");
    expect(styles.text).toContain(".character-markdown-editor > .vditor-editor-host.vditor:focus-within");
    expect(application.text).toContain('placeholder: "从这里开始写 Markdown 设定…"');
    expect(application.text).toContain('placeholder: "从这里开始写人物章节…"');
    expect(application.text.match(/width: "100%"/gu)).toHaveLength(2);
    expect(styles.text).toContain("#knowledge-editor-form { display: grid; grid-template-rows: auto minmax(0, 1fr) auto; }");
    expect(styles.text).toContain(".vditor-editor-host .vditor");
    expect(styles.text).toContain(".setting-editor-title-input");
    expect(styles.text).toContain(".setting-editor-header-fields");
    expect(styles.text).toContain(".character-section-editor-title-input");
    expect(application.text).toContain('class="character-section-editor-title-input"');
    expect(application.text).toContain('class="character-section-editor-title-input" maxlength="200" value="${esc(section?.title ?? "")}"');
    expect(application.text).toContain('class="character-markdown-editor knowledge-markdown-editor"');
    expect(application.text).not.toContain('<label>设定标题<input id="knowledge-section-title"');
    expect(application.text).not.toContain('<label>章节标题<input id="character-section-title"');
    expect(styles.text).toContain(".character-relationship-row");
    expect(styles.text).toContain(".keyword-chip-editor");
    expect(styles.text).toContain(".character-version-card");
    expect(styles.text).toContain(".character-aliases { display: flex;");
    expect(styles.text).toContain(".character-code .pill { display: inline-flex; align-items: center; justify-content: center;");
    expect(styles.text).toContain(".character-species, .character-gender { display: grid;");
    expect(styles.text).toContain(".character-species .pill, .character-gender .pill { display: inline-flex; align-items: center; justify-content: center;");
    expect(styles.text).toContain(".card-actions .danger-button");
    expect(styles.text).toContain(".merge-dialog-note");
  });

  it("首屏书架、大纲伏笔、续写守卫和关系银河图资源完整可达", async () => {
    const page = await request(runtime.app).get("/").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);
    const analysisTypes = await request(runtime.app).get("/analysis-types.js").expect(200);
    const modelConfig = await request(runtime.app).get("/model-config.js").expect(200);
    const connectivityTest = await request(runtime.app).get("/ai-connectivity-test.js").expect(200);
    const aiUsage = await request(runtime.app).get("/ai-usage.js").expect(200);
    const graph = await request(runtime.app).get("/relationship-graph.js").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    const workPermissions = await request(runtime.app).get("/work-permissions.js").expect(200);
    const keyboardShortcuts = await request(runtime.app).get("/keyboard-shortcuts.js").expect(200);
    const markdown = await request(runtime.app).get("/markdown.js").expect(200);
    const vditorCss = await request(runtime.app).get("/vendor/vditor/dist/index.css").expect(200);
    const vditorScript = await request(runtime.app).get("/vendor/vditor/dist/index.min.js").expect(200);
    const icon = await request(runtime.app).get("/icon.svg").expect(200).expect("Content-Type", /svg/u);
    const manifest = await request(runtime.app).get("/site.webmanifest").expect(200);
    expect(page.text).toContain('id="shelf-view"');
    expect(page.text).toContain('id="platform-ai-view"');
    expect(page.text).toContain('id="platform-ai-button"');
    expect(page.text).toContain('id="platform-usage-view"');
    expect(page.text).toContain('id="platform-usage-pricing-refresh"');
    expect(page.text).toContain('id="platform-usage-button"');
    expect(page.text).toContain('feature=ai-token-usage-details-centered-v1');
    expect(page.text).toContain('rel="icon" href="/icon.svg?v=20260712"');
    expect(page.text).toContain('rel="manifest" href="/site.webmanifest"');
    expect(page.text).toContain('/vendor/vditor/dist/index.css?v=3.11.2');
    expect(page.text).toContain('/vendor/vditor/dist/js/icons/ant.js?v=3.11.2');
    expect(page.text).toContain('/vendor/vditor/dist/index.min.js?v=3.11.2');
    expect(page.text).toContain('/styles.css?v=20260816-task-scope-volume-collapse-v2');
    expect(styles.text).toContain('.brand-mark { display: grid; place-items: center; width: 34px; height: 34px; color: #fff; border-radius: 3px; font-weight: 700; }');
    expect(page.text).toContain('/app.js?v=20260816-extended-thinking-effort-v1');
    expect(page.text).toContain('feature=ai-provider-thinking-type-v1');
    expect(page.text).toContain('feature=ai-provider-analysis-timeout-v1');
    expect(application.text).toContain('if (state.chapter?.id === route.chapterId && $("#editor-view").classList.contains("hidden")) await selectChapter(state.chapter.id);');
    expect(application.text).toContain('/api/platform/ai/usage?timezoneOffset=');
    expect(application.text).toContain('/ai-settings/usage?timezoneOffset=');
    expect(application.text).toContain('class="form-field model-multimodal-fields"');
    expect(application.text).toContain('class="checkbox-field model-capability-option"');
    expect(application.text).toContain('模型供应商配置');
    expect(application.text).toContain('const multimodalFields = imageDefaultSupported ?');
    expect(application.text).toContain('/ai-connectivity-test.js?v=20260822-private-ai-endpoint-hint-v1');
    expect(connectivityTest.text).toContain('图片请求已验证');
    expect(connectivityTest.text).toContain('接下来 2 分钟内不能再次测试');
    expect(connectivityTest.text).toContain('当前地址指向本机或内网，已允许连接，请确认该地址可信');
    expect(application.text).toContain('发送一张测试图片验证图片请求');
    expect(application.text).toContain('configureTokenQuotaInput(host.querySelector("#daily-token-quota"), "daily-token-quota-warning", 10_000)');
    expect(application.text).toContain('<label class="checkbox-field config-checkbox-field"><input id="daily-token-quota-enabled"');
    expect(application.text).toContain('configureTokenQuotaInput(host.querySelector("#monthly-token-quota"), "monthly-token-quota-warning", 1_000_000)');
    expect(application.text).toContain('<label class="checkbox-field config-checkbox-field"><input id="monthly-token-quota-enabled"');
    expect(application.text).toContain('ai 小说用量巨大，低用量基本等于不可用');
    expect(application.text).toContain('value <= 0');
    expect(application.text).toContain('每日 Token 额度必须设置大于 0 的整数');
    expect(application.text).toContain('每月 Token 额度必须设置大于 0 的整数');
    expect(application.text).toContain('后端部署时区（${esc(quotaTimezone)}）');
    expect(application.text).toContain('body: { dailyTokenQuota: enabled ? quota : null }');
    expect(application.text).toContain('body: { monthlyTokenQuota: enabled ? quota : null }');
    expect(application.text).toContain('/page-route.js?v=20260812-reader-preview-v1');
    expect(application.text).toContain("本书 Token 用量");
    expect(application.text).toContain("formatEstimatedCost");
    expect(application.text).toContain("估价");
    expect(application.text).toContain("根据多来源模型价格表估算");
    expect(application.text).toContain("pricingAvailable === true");
    expect(application.text).toContain("Cache Read");
    expect(application.text).toContain("Cache Write");
    expect(application.text).toContain("估算价格");
    expect(application.text).toContain('data-token-usage-details');
    expect(application.text).toContain('function showTokenUsageDetails(usage, title, trigger)');
    expect(application.text).toContain('classList.add("token-usage-details-region")');
    expect(application.text).toContain('["directInputTokens", "cacheWriteInputTokens", "cacheReadInputTokens"');
    expect(application.text).toContain('"Raw Input"');
    expect(application.text).toContain("/api/platform/ai/usage/pricing/refresh");
    expect(application.text).toContain('state.user?.role !== "admin"');
    expect(application.text).toContain("有 ${unpricedModelCount.toLocaleString(\"zh-CN\")} 个模型在价格表中未找到对应价格");
    expect(application.text).toContain('"work-usage-calendar-title"}">每日用量</h3>');
    expect(application.text).toContain("calendar.scrollLeft = calendar.scrollWidth");
    expect(application.text).toContain('class="usage-calendar-tooltip" role="tooltip" hidden');
    expect(application.text).toContain('cell.addEventListener("mouseenter", () => showTooltip(cell))');
    expect(application.text).toContain('cell.addEventListener("click", () => showTooltip(cell))');
    expect(styles.text).toContain('.usage-calendar-tooltip { position: absolute;');
    expect(aiUsage.text).toContain("export function buildUsageCalendar");
    expect(page.text).toContain('<body>');
    expect(page.text).toContain('id="auth-view" class="auth-view hidden"');
    expect(page.text).toContain('<html lang="zh-CN" class="dev-auth-bypass">');
    expect(page.text.match(/<img class="brand-mark" src="\/icon\.svg\?v=20260712" alt="">/gu)).toHaveLength(2);
    expect(page.text).toContain('id="presence-button"');
    expect(page.text).toContain('<span id="presence-count">1 人</span>');
    expect(page.text).not.toContain('id="presence-count">1 人在线</span>');
    expect(page.text).toContain('id="presence-list"');
    expect(application.text).toContain("function handleCollaborativeChanges(recentChanges)");
    expect(application.text).toContain('const changeLabel = latest.label || "当前页面"');
    expect(application.text).toContain('const deleted = latest.action === "delete"');
    expect(application.text).toContain('title: deleted ? `${targetLabel}已删除` : `${changeLabel}已更新`');
    expect(application.text).toContain("function reloadAfterCollaborativeChange(change)");
    expect(application.text).toContain('change?.action === "delete" && change.pageDeleted && workId');
    expect(application.text).not.toContain('localKey.startsWith("entity-editor:relationship:")');
    expect(application.text).not.toContain("peerPageStale");
    expect(styles.text).toContain(".dev-auth-bypass .auth-view { display: none !important; }");
    expect(styles.text).toContain(".dev-auth-bypass .auth-loading { display: none !important; }");
    expect(styles.text).toContain(".shelf-header { display: flex; align-items: flex-end; justify-content: space-between; gap: 30px; width: 100%;");
    expect(styles.text).toContain(".shelf-header .primary-button { align-self: flex-start; min-width: 150px; min-height: 40px; padding: 8px 18px; }");
    expect(styles.text).toContain("width: 90%; margin-inline: auto; aspect-ratio: 3 / 4.25;");
    expect(styles.text).toContain(".settings-hub-header h1 { font-size: clamp(26px, 3vw, 36px); line-height: 1.15; letter-spacing: -.02em; }");
    expect(styles.text).toContain(".settings-hub-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));");
    expect(styles.text).toContain(".settings-hub-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }");
    expect(styles.text).toContain(".usage-calendar-grid {");
    expect(styles.text).toContain(".usage-stat-grid {");
    expect(styles.text).toContain(".usage-cost-bubble {");
    expect(styles.text).toContain(".toast-region.token-usage-details-region");
    expect(styles.text).toContain(".token-usage-details-table {");
    expect(styles.text).toContain("@container usage-overview (max-width: 760px)");
    expect(page.text).toContain('id="platform-ai-return"');
    expect(page.text).toContain('id="users-settings-return"');
    expect(page.text).toContain('id="platform-ui-settings-return"');
    expect(page.text).toContain('id="members-settings-return" class="ghost-button settings-parent-button hidden"');
    expect(page.text).toContain('id="appearance-settings-return"');
    expect(application.text).toContain('async function returnToSettingsHub(actionSelector, dialogSelector = null)');
    expect(application.text).toContain('$("#members-settings-return").classList.toggle("hidden", $("#settings-hub-view").classList.contains("hidden"));');
    expect(styles.text).toContain('.settings-detail-actions, .settings-dialog-header-actions { display: flex; align-items: center; gap: 10px; }');
    expect(styles.text).toContain(':is(#users-dialog, #platform-ui-settings-dialog, #members-dialog, #appearance-dialog) select:not([multiple]) {');
    expect(styles.text).toContain('background-position: right 21px center, right 16px center;');
    expect(keyboardShortcuts.text).toContain("export function isGlobalSearchShortcut(event)");
    expect(application.text).toContain("if (!isGlobalSearchShortcut(event) || !state.work) return;");
    expect(page.text).not.toContain('class="setting-markdown-heading"');
    expect(application.text).not.toContain('在这里完整记录设定内容');
    expect(application.text).not.toContain('支持标题、列表、引用、表格、链接和图片');
    expect(styles.text).toContain('.setting-editor-content { height: 100%; min-height: 0; padding: 16px clamp(16px, 2vw, 32px) 24px; overflow: hidden; }');
    expect(application.text).toContain("if (readOnly) editor?.disabled();");
    expect(application.text).not.toContain("if (readOnly) editor.disabled();");
    expect(application.text).toContain('/relationship-graph.js?v=20260817-relationship-canvas-scale-v1');
    expect(application.text).toContain('<td>${item.evidence.length}</td><td>${Math.round(item.confidence * 100)}%</td>');
    expect(application.text).not.toContain('${item.evidence.length} 条');
    expect(graph.text).toContain('path.setAttribute("marker-end", `url(#${arrowMarkerId})`)');
    expect(graph.text).toContain("assignRelationshipEdgeCurves(graph.edges)");
    expect(graph.text).toContain('statuses.push("待确认")');
    expect(graph.text).toContain('selection.endpointNames.join(selection.directed ? " → " : " ↔ ")');
    expect(application.text).toContain('/race-hierarchy.js?v=20260729-race-tree-all-v1');
    expect(application.text).toContain('const roots = await moduleApi("races", `/api/works/${workId}/races?scope=roots`);');
    expect(application.text).toContain('renderRaceCollection(roots.total, loadedRaceHierarchyWorkId !== workId);');
    expect(application.text).toContain('const dismissLoadingToast = persistentToast("正在加载子种族……");');
    expect(application.text).toContain('moduleApi("races", `/api/works/${workId}/races?scope=descendants`)');
    expect(application.text).toContain('state.races = [...roots.items, ...descendants];');
    expect(application.text).toContain('aria-busy="${descendantsLoading}"');
    expect(application.text).not.toContain("paginateRaceForest");
    expect(graph.text).toContain('fullscreen.className = "ghost-button relationship-galaxy-button"');
    expect(graph.text).toContain('class="relationship-galaxy-icon"');
    expect(graph.text).toContain('aria-label", "全屏银河图"');
    expect(styles.text).toContain(".relationship-galaxy-icon {");
    expect(styles.text).toContain(".relationship-table .relationship-actions button");
    expect(page.text).toContain('id="avatar-file"');
    expect(page.text).toContain('accept="image/png,image/jpeg,image/webp"');
    expect(page.text).toContain("文件不超过 2 MB");
    expect(page.text).toContain('id="profile-avatar-preview"');
    expect(page.text).toContain('id="avatar-upload-button"');
    expect(page.text).toContain('id="avatar-remove-button"');
    expect(page.text).toContain('id="avatar-crop-dialog"');
    expect(page.text).toContain('id="avatar-crop-confirm"');
    expect(page.text).toContain("选择后可框选正方形选区再裁剪上传");
    expect(application.text).toContain('/avatar-crop.js?v=20260725-avatar-crop');
    expect(application.text).toContain("async function openAvatarCropDialog(file)");
    expect(application.text).toContain("const defaultImageUploadLimits = {");
    expect(application.text).toContain("imageUploadLimits.attachmentBytes");
    expect(application.text).toContain("imageUploadLimits.chatImageBytes");
    expect(application.text).toContain("封面不支持 GIF 图片");
    expect(application.text).toContain("支持 PNG、JPEG、WebP；文件不超过");
    expect(application.text).toContain("uploadWithProgress");
    expect(application.text).toContain("renderAvatarUploadProgress");
    expect(application.text).toContain("renderWorkCoverUploadProgress");
    expect(application.text).toContain("showScrollbarWhileScrolling");
    expect(application.text).toContain("scrollBarHideDelay = 650");
    expect(page.text).toContain('id="cover-file"');
    expect(page.text).toContain('accept="image/png,image/jpeg,image/webp"');
    expect(application.text).toContain('uploadWithProgress("/api/auth/avatar", { method: "PUT", body }');
    expect(application.text).toContain('api("/api/auth/avatar", { method: "DELETE" })');
    expect(application.text).toContain("function renderUserAvatar(element, user)");
    expect(styles.text).toContain(".profile-avatar-preview");
    expect(styles.text).toContain(".avatar-crop-selection");
    expect(styles.text).toContain(".avatar-crop-preview");
    expect(page.text).toContain('id="api-key-reset-button"');
    expect(page.text).toContain('id="api-key-copy-button" class="ghost-button" type="button" hidden aria-label="复制 API Key"');
    expect(page.text).toContain("完整 Key 不会显示在页面上，可随时复制");
    expect(page.text).not.toContain('id="api-key-value"');
    expect(page.text).not.toContain("新 Key 仅显示一次");
    expect(page.text).toContain("feature=api-key-copy-existing-v1");
    expect(styles.text).toContain(".api-key-actions button { display: inline-flex; align-items: center; gap: 6px; min-height: 38px; }");
    expect(application.text).toContain('api("/api/auth/api-key/reset"');
    expect(application.text).toContain('api("/api/auth/api-key/reveal"');
    expect(application.text).toContain("function paintApiKeyStatus(status)");
    expect(application.text).not.toContain("$(\"#api-key-value\")");
    expect(application.text).toContain("/toast-layer.js?v=20260822-toast-modal-host-v1");
    expect(application.text).toContain("function syncToastRegionHost()");
    expect(application.text).toContain('/analysis-types.js?v=20260721-analysis-descriptions');
    expect(analysisTypes.text).toContain('label: "世界观分析"');
    expect(analysisTypes.text).toContain('desc: "归纳正文中的自然、社会、历史、科技、文化等世界观维度，同时标出冲突和证据不足之处。"');
    expect(styles.text).toContain(".analysis-type-description");
    expect(page.text).toContain('id="setting-editor-confirm"');
    expect(application.text).toContain('review: "已完成"');
    expect(application.text).toContain('failed: "失败"');
    expect(application.text).toContain('/background-task-center.js?v=20260817-analysis-task-expired-toast-v1');
    expect(application.text).toContain('if (transition.status === "failed") return { message: `${label}失败，请打开任务详情查看`, type: "error" };');
    expect(application.text).not.toContain('review: "待审核"');
    expect(application.text).toContain('"分析已完成"');
    expect(application.text).not.toContain("结果进入审核状态");
    expect(styles.text).toContain("--toast-bg:");
    expect(styles.text).toContain(".task-status-badge.is-partial, .task-status-badge.is-failed");
    expect(styles.text).toContain(":root[data-theme=\"dark\"]");
    expect(styles.text).toContain("--relationship-network-surface: #eef2f7");
    expect(styles.text).toContain("--relationship-network-surface: #12121a");
    expect(styles.text).toContain("--node-color: var(--node-color-light, #626b78)");
    expect(styles.text).toContain(':root[data-theme="dark"] .relationship-network .mind-node');
    expect(graph.text).toContain('button.style.setProperty("--node-color-dark", node.darkColor || appearance.darkColor)');
    expect(styles.text).toContain(".relationship-network-card .relationship-map-toolbar");
    expect(styles.text).toContain("background: var(--toast-bg)");
    expect(page.text).toContain('id="platform-ui-settings-button" class="settings-hub-card hidden"');
    expect(page.text).toContain('id="platform-ui-settings-dialog"');
    expect(page.text).toContain('id="galaxy-frame-rate"');
    expect(page.text).toContain('<option value="90">90 FPS（高刷新率）</option>');
    expect(page.text).toContain('<option value="120">120 FPS（超高刷新率）</option>');
    expect(page.text).toContain('<option value="144">144 FPS（电竞显示器）</option>');
    expect(page.text).toContain('<option value="165">165 FPS（高刷显示器）</option>');
    expect(page.text).toContain('<option value="240">240 FPS（最高档）</option>');
    expect(page.text).toContain('id="page-size-settings"');
    expect(page.text).toContain('id="page-size-characters"');
    expect(page.text).not.toContain('id="page-size-races"');
    expect(page.text).toContain('id="page-size-organizations"');
    expect(page.text).toContain('id="page-size-timeline"');
    expect(page.text).toContain('id="page-size-outlines"');
    expect(page.text).toContain('id="page-size-relationships"');
    expect(page.text).toContain('id="page-size-comments"');
    expect(page.text).toContain('id="page-size-reviews"');
    expect(page.text).toContain('id="page-size-analysis-tasks"');
    expect(page.text).toContain('id="page-size-file-versions"');
    expect(page.text).toContain('种族层级始终完整展示');
    expect(page.text).toContain('data-position="bottom-right"');
    expect(application.text).toContain('api("/api/ui-settings")');
    expect(application.text).toContain('api("/api/platform/ui-settings"');
    expect(application.text).toContain('pageSizes: {');
    expect(application.text).toContain('galaxyFrameRate: Number($("#galaxy-frame-rate").value)');
    expect(application.text).toContain('function paginateModuleItems(items, page, sizeKey)');
    expect(application.text).toContain('renderModulePagination(pageResult, "settings", "设定库")');
    expect(application.text).not.toContain('renderModulePagination(pageResult, "races", "种族列表")');
    expect(application.text).toContain('renderModulePagination(pageResult, "organizations", "组织列表")');
    expect(application.text).toContain('renderModulePagination(pageResult, "timeline", "时间线事件")');
    expect(application.text).toContain('renderModulePagination(pageResult, "relationships", "人物关系列表")');
    expect(application.text).toContain('renderModulePagination(pageResult, "reviews", "审核列表")');
    expect(styles.text).toContain('.pagination-settings-grid { display: grid;');
    expect(styles.text).toContain('.toast-region[data-position="top-right"]');
    expect(styles.text).toContain('.toast-region[data-position="bottom-right"]');
    expect(styles.text).not.toContain(".task-table .task-id");
    expect(application.text).not.toContain("<th>ID</th><th>任务</th>");
    expect(page.text).toContain('id="top-search-button"');
    expect(page.text).toContain('title="全文检索（Command/Ctrl+F）"');
    expect(page.text).toContain('id="user-management-button" class="settings-hub-card hidden"');
    expect(page.text).toContain('id="writing-progress-button" class="settings-hub-card"');
    expect(page.text).toContain('id="writing-progress-dialog"');
    expect(application.text).toContain("function renderWritingProgress(");
    expect(application.text).toContain("async function saveWritingGoal(");
    expect(styles.text).toContain(".writing-trend-chart");
    expect(styles.text).toContain(".dialog.writing-progress-dialog { width: min(900px, 94vw); }");
    expect(styles.text).toContain(".writing-trend-bar i { display: block; justify-self: center; width: clamp(4px, 68%, 14px);");
    expect(styles.text).toContain(".writing-goal-fields input { width: 100%; min-height: 38px;");
    expect(styles.text).toContain("font: 7px/22px var(--font-latin), monospace;");
    expect(styles.text).toContain(".writing-trend-tooltip { position: absolute;");
    expect(styles.text).toContain(".writing-trend-daily-line polyline { fill: none; stroke: var(--green);");
    expect(styles.text).toContain(".writing-trend-daily-points i { position: absolute;");
    expect(styles.text).toContain(".writing-trend-legend { position: absolute; z-index: 2; top: -27px;");
    expect(application.text).toContain('id="writing-trend-tooltip" class="writing-trend-tooltip" role="tooltip" hidden');
    expect(application.text).toContain('class="writing-trend-daily-line"');
    expect(application.text).toContain('class="writing-trend-daily-points"');
    expect(application.text).toContain("当日新增");
    expect(application.text).toContain("const dailyWords = Math.max(0, Number(item.delta));");
    expect(application.text).toContain('bar.addEventListener("mouseenter", () => showTooltip(bar))');
    expect(page.text).toContain('id="work-audit-button" class="settings-hub-card"');
    expect(page.text).toContain('<span class="settings-card-mark">出</span><strong>导出正文</strong><small>选择 Markdown ZIP、DOCX 或 EPUB；不包含角色和设定资料</small>');
    expect(page.text).toContain('id="manuscript-export-menu" class="manuscript-export-menu hidden" role="menu" aria-label="导出正文格式"');
    expect(page.text).toContain('data-export-format="markdown"');
    expect(page.text).toContain('data-export-format="docx"');
    expect(page.text).toContain('data-export-format="epub"');
    expect(application.text).toContain('id="work-export-button" class="ghost-button" type="button" aria-haspopup="menu" aria-controls="manuscript-export-menu" aria-expanded="false">导出正文</button>');
    expect(application.text).toContain('function showManuscriptExportMenu(anchor, work)');
    expect(application.text).toContain('function downloadWorkManuscript(work, format = "markdown", trigger = null)');
    expect(application.text).toContain('function downloadVolumeEpub(volume, trigger)');
    expect(application.text).toContain('method: "HEAD", headers: { Accept: "application/epub+zip" }');
    expect(application.text).toContain('EPUB 下载已开始');
    expect(application.text).toContain('EPUB 导出失败：');
    expect(application.text).not.toContain('data-export-volume="${esc(volume.id)}"');
    expect(application.text).toContain('不包含角色、设定、关系、时间轴、大纲、伏笔或 AI 分析资料');
    expect(styles.text).toContain('.manuscript-export-menu');
    expect(styles.text).not.toContain('.volume-export-button');
    expect(page.text).toContain('id="work-audit-view" class="shelf-view work-audit-view hidden"');
    expect(page.text).toContain('id="work-audit-return" class="ghost-button settings-parent-button"');
    expect(page.text).not.toContain('id="work-audit-dialog"');
    expect(application.text).toContain("async function showWorkAudit(");
    expect(application.text).toContain('replacePageRoute({ view: "work-audit"');
    expect(application.text).toContain("workAuditActionLabels");
    expect(styles.text).toContain(".work-audit-row { display: grid; grid-template-columns: minmax(160px, 190px) minmax(0, 1fr);");
    expect(styles.text).toContain(".work-audit-time strong { color: var(--ink); font-size: 18px;");
    expect(styles.text).toContain(".work-audit-event-heading strong { color: var(--ink); font-size: 17px;");
    expect(page.text).toContain('id="search-dialog"');
    expect(page.text).toContain('id="search-query" name="query" type="search" maxlength="100"');
    expect(application.text).toContain('isGlobalSearchShortcut(event)');
    expect(application.text).toContain('const target = resolveGlobalSearchTarget(result);');
    expect(application.text).toContain('await selectChapter(target.id);');
    expect(application.text).toContain('const item = await api(target.apiPath);');
    expect(application.text).toContain('openSettingEditor(item, { readOnly: true });');
    expect(application.text).toContain('await openCharacterEditor(item, { readOnly: true });');
    expect(application.text).toContain('await openRaceDialog(item, { readOnly: true });');
    expect(application.text).toContain('await openOrganizationDialog(item, { readOnly: true });');
    expect(application.text).toContain('{ capture: true }');
    expect(page.text).not.toContain('id="search-button"');
    expect(page.text).toContain('class="prompt-composer"');
    expect(page.text).toContain('class="ai-send-button"');
    expect(page.text).toContain('id="ai-context-meter"');
    expect(application.text).toContain('description.textContent = item.key === "skills" ? "待加入" : "用户和 agent 的交互";');
    expect(application.text).toContain("function scheduleChapterAutoSave(delay = chapterAutoSaveDelay)");
    expect(application.text).toContain("多人协作，自动保存已关闭");
    expect(application.text).toContain("if (automatic) {");
    expect(application.text).toContain("await refreshPresence();");
    expect(application.text).toContain('source: automatic ? "auto" : "manual"');
    expect(markdown.text).toContain("export function renderMarkdown");
    expect(markdown.text).toContain("safeLinkTarget");
    expect(markdown.text).toContain("renderMarkdownTable");
    expect(vditorCss.text).toContain("Vditor v3.11.2");
    expect(vditorScript.text).toContain("Vditor");
    expect(application.text).toContain('/markdown.js?v=20260731-no-external-images-v1');
    expect(application.text).toContain('/upload-progress.js?v=20260812-upload-progress-v1');
    expect(application.text).toContain('new window.Vditor');
    expect(application.text).toContain('createVditorUploadHandler');
    expect(application.text).toContain('createVditorUploadPlaceholder');
    expect(page.text).toContain('id="character-section-editor-view"');
    expect(page.text).toContain('id="knowledge-section-editor-view"');
    expect(application.text).toContain('id="character-section-markdown"');
    expect(application.text).toContain("attachment://${attachment.id}");
    expect(application.text).toContain("preview: { transform: transformVditorPreview }");
    expect(application.text).toContain("/api/attachments/${encodeURIComponent(attachmentId)}/content");
    expect(application.text).toContain("function normalizeVditorAttachmentImages");
    expect(application.text).toContain("editor.__attachmentObserver = attachmentObserver");
    expect(application.text).toContain("read_character_sections");
    expect(application.text).toContain('role="note" aria-label="保存角色提示"');
    expect(application.text).toContain("请先保存当前角色");
    expect(application.text).toContain("保存成功后即可新建 Markdown 档案章节");
    expect(styles.text).toContain(".message-body .markdown-table-scroll");
    expect(page.text).toContain('id="markdown-table-menu"');
    expect(application.text).toContain('openMarkdownTableMenu(header, event.clientX, event.clientY)');
    expect(styles.text).toContain(".message-body .markdown-table-scroll.is-wrapping table");
    expect(styles.text).toContain('.vditor-editor-host.vditor--dark .vditor-reset table { background: var(--surface); color: var(--ink); }');
    expect(styles.text).toContain('.vditor-editor-host.vditor--dark .vditor-reset table tbody tr:nth-child(2n) { background: var(--surface-soft); }');
    expect(styles.text).toContain(".vditor-upload-queue {");
    expect(styles.text).toContain(".image-upload-progress-panel {");
    expect(styles.text).toContain("* { scrollbar-width: thin; scrollbar-color: transparent transparent; }");
    expect(styles.text).toContain("*::-webkit-scrollbar { width: 8px; }");
    expect(styles.text).toContain(".is-scrollbar-visible::-webkit-scrollbar-thumb {");
    expect(styles.text).not.toContain("* { scrollbar-width: none; }");
    expect(styles.text).not.toContain("*::-webkit-scrollbar { width: 0; }");
    expect(styles.text).toContain(".character-markdown-editor > .vditor-editor-host");
    expect(styles.text).toContain("#character-section-editor-view");
    expect(styles.text).toContain("#knowledge-section-editor-view");
    expect(styles.text).toContain("scrollbar-gutter: stable");
    expect(styles.text).toContain("white-space: nowrap");
    expect(icon.body.toString("utf8")).toContain("一本展开的书与一颗星");
    expect(manifest.body.short_name).toBe("叙界");
    expect(page.text).toContain('data-testid="book-shelf"');
    expect(application.text).toContain('data-testid="book-add-card"');
    expect(application.text).toContain('id="work-access-title">成员权限</strong>');
    expect(application.text).toContain('id="work-access-manage"');
    expect(application.text).toContain('按成员配置</span><span>按模块授权</span><span>读写分离</span>');
    expect(page.text).toContain('id="member-user-select"');
    expect(page.text).toContain('id="member-permission-fieldset"');
    expect(page.text).toContain('id="member-permission-grid"');
    expect(page.text).toContain('data-permission-preset="read"');
    expect(application.text).toContain('data-member-permission=');
    expect(application.text).toContain('body: existing ? { permissions } : { userId, permissions }');
    expect(application.text).toContain('/work-permissions.js?v=20260818-annotation-permissions-v1');
    expect(workPermissions.text).toContain('label: "AI 对话"');
    expect(workPermissions.text).toContain('label: "AI 分析"');
    expect(workPermissions.text).toContain('id: "ai-chat"');
    expect(workPermissions.text).toContain('id: "ai-analysis"');
    expect(workPermissions.text).toContain('export function canWritePermissionModule');
    expect(workPermissions.text).toContain('export function canWriteUiModule');
    expect(application.text).toContain('classList.toggle("view-only-mode", viewOnly)');
    expect(application.text).toContain('classList.toggle("prose-hidden-mode", proseHidden)');
    expect(application.text).toContain('if (!item.uiModule) continue;');
    expect(application.text).toContain('canReadPermissionModule(state.work, "ai-chat")');
    expect(application.text).toContain('$("#module-nav [data-work-settings]").classList.toggle("permission-hidden"');
    expect(application.text).toContain('$("#new-volume-button").classList.toggle("permission-hidden", Boolean(state.work) && proseReadOnly)');
    expect(application.text).toContain('$("#welcome-new-work").classList.toggle("permission-hidden", Boolean(state.work) && proseReadOnly)');
    expect(application.text).toContain('$(".ai-panel").classList.toggle("permission-hidden", aiHidden)');
    expect(styles.text).toContain("body.work-viewer-mode [data-edit-setting]");
    expect(styles.text).toContain("body.work-viewer-mode [data-merge-review]");
    expect(application.text).toContain('item.status === "pending" && canResolveReview');
    expect(application.text).toContain('canReadCharacters && hasCharacterDuplicateReviews');
    expect(application.text).toContain('const canReadAggregate = hasWork && canReadAggregateContent()');
    expect(styles.text).not.toContain(".app-shell.prose-read-only-mode:not(.shelf-mode) #new-chapter-button");
    expect(styles.text).toContain(".add-button { width: 24px; height: 24px;");
    expect(styles.text).toContain(".member-permission-grid");
    expect(styles.text).toContain(".work-access-options");
    expect(application.text).toContain('class="book-card-settings"');
    expect(application.text).toContain("function workCoverFieldHtml(work)");
    expect(application.text).toContain('id="work-cover-upload"');
    expect(application.text).not.toContain("book-card-actions");
    expect(application.text).not.toContain("本书追加系统提示词");
    expect(application.text).toContain('aria-label="本书系统提示词"');
    expect(application.text).toContain("modelOptionLabel({ ...model, providerName: model.providerName || provider?.name })");
    expect(application.text).not.toContain("${esc(model.displayName)} · ${esc(model.modelId)}");
    expect(application.text).toContain("function openTaskDetailDialog(task, trace)");
    expect(application.text).toContain('$("#dialog-fields").scrollTop = 0;');
    expect(application.text).toContain('id="task-auto-run-enabled"');
    expect(application.text).toContain('let taskAutoRunEditing = false;');
    expect(application.text).toContain('const autoRunEditing = canConfigureAutoRun && taskAutoRunEditing');
    expect(application.text).toContain('id="task-auto-run-edit"');
    expect(application.text).toContain('id="task-auto-run-edit" class="record-card-edit"');
    expect(application.text).toContain('aria-label="编辑自动执行设置"');
    expect(application.text).toContain('function renderTaskScopeSummary(task)');
    expect(application.text).toContain('data-task-scope-target');
    expect(application.text).toContain('await selectChapter(targetId);');
    expect(application.text).toContain('await openCharacterEditor(character, { readOnly: true });');
    expect(application.text).toContain('function bindTaskResultReferenceActions(container)');
    expect(application.text).toContain('data-task-result-reference');
    expect(application.text).toContain('await api(`/api/settings/${encodeURIComponent(referenceId)}`);');
    expect(application.text).toContain('class="task-auto-run-header"');
    expect(application.text).toContain('class="task-auto-run-actions"');
    expect(application.text).toContain('id="task-auto-run-pause"');
    expect(application.text).toContain('body: { autoRunEnabled: false }');
    expect(application.text).toContain("自动执行待分析任务");
    expect(application.text).toContain("不会自动创建人物关系、世界观或其他分析");
    expect(application.text).toContain("开启后会持续执行直到队列清空");
    expect(application.text).toContain("同时运行上限");
    expect(application.text).toContain("每日任务上限");
    expect(application.text).toContain("连续失败暂停阈值");
    expect(application.text).toContain('id="task-auto-run-stability-delay"');
    expect(application.text).toContain("停止编辑后创建任务");
    expect(application.text).toContain("稳定窗口");
    expect(application.text).toContain("恢复自动执行");
    expect(application.text).not.toContain("每轮任务上限");
    expect(application.text).not.toContain("开始下一轮");
    expect(application.text).toContain('class="task-auto-run-progress ${activeTaskCount ? "" : "hidden"}"');
    expect(application.text).toContain('class="task-auto-run-progress-ring ${queueProgressClass}" role="progressbar"');
    expect(application.text).toContain('class="task-auto-run-progress-ring-value" cx="60" cy="60" r="52" pathLength="100" stroke-dasharray="${runningProgress} 100"');
    expect(application.text).toContain('class="task-auto-run-progress-bar ${queueProgressClass}" max="100" value="${runningProgress}"');
    expect(application.text).toContain("scheduleTaskProgressRefresh(state.work.id, runningCount > 0 || (pendingCount > 0 && autoRunActive) ? 1 : 0)");
    expect(application.text).toContain("scheduleTaskProgressRefresh(workId, 1)");
    expect(application.text).toContain('const optimisticTask = { id: button.dataset.runTask, status: "running", progress: 5 };');
    expect(application.text).toContain("statusCell.innerHTML = renderAnalysisTaskStatus(optimisticTask)");
    expect(application.text).toContain("progressCell.innerHTML = renderAnalysisTaskProgress(optimisticTask)");
    expect(application.text).not.toContain("消化 pending 任务");
    expect(application.text).toContain("/tasks/auto-run");
    expect(styles.text).toContain(".task-auto-run-panel");
    expect(styles.text).toContain("grid-template-columns: minmax(0, 1fr) 268px;");
    expect(styles.text).toContain(".task-auto-run-header { display: grid; grid-column: 1 / -1;");
    expect(styles.text).toContain("position: absolute;\n  top: 50%;\n  right: 90px;");
    expect(styles.text).toContain("transform: translateY(-50%);");
    expect(styles.text).toContain("width: 184px;");
    expect(styles.text).toContain(".task-auto-run-progress-ring { position: relative; display: grid; width: 184px; height: 184px;");
    expect(styles.text).toContain(".task-auto-run-actions { display: flex; align-items: start;");
    expect(styles.text).not.toContain(".task-auto-run-actions { display: flex; grid-column: 2;");
    expect(styles.text).toContain(".task-auto-run-progress-ring-value { stroke: var(--accent);");
    expect(styles.text).toContain(".task-auto-run-progress-ring { display: none; }");
    expect(styles.text).toContain(".task-auto-run-progress-bar-layout { display: grid;");
    expect(styles.text).toContain(".task-auto-run-progress-bar::-webkit-progress-value");
    expect(styles.text).toContain(".task-scope-link, .task-reference-link {");
    expect(application.text).toContain('class="task-status-badge is-${status}${statusChanged ? " is-state-change" : ""}"');
    expect(application.text).toContain('class="task-progress-track" role="progressbar"');
    expect(styles.text).toContain(".task-status-badge.is-running");
    expect(styles.text).toContain("--task-running: #356f94;");
    expect(styles.text).toContain("--task-running: #7fb8d8;");
    expect(styles.text).toContain("--task-status-color: var(--task-running);");
    expect(styles.text).toContain(".task-progress.is-running .task-progress-fill { background: var(--task-running); }");
    expect(styles.text).toContain(".task-progress.is-review .task-progress-fill, .task-progress.is-completed .task-progress-fill { background: var(--green); }");
    expect(styles.text).toContain("@keyframes task-status-running-breathe");
    expect(styles.text).toContain("@keyframes task-progress-waiting");
    expect(styles.text).toContain("@media (prefers-reduced-motion: reduce)");
    expect(application.text).toContain("memberDialogWork ?? state.work");
    expect(application.text).toContain('const platformDocumentTitle = "叙界 · 小说 AI 创作工作台"');
    expect(application.text).toContain('document.title = workTitle ? `${workTitle} · 叙界` : platformDocumentTitle');
    expect(application.text).toContain("updateDocumentTitle(state.work)");
    expect(page.text).toContain('data-module="races"');
    expect(page.text).toContain('</svg>种族</button>');
    expect(page.text).toContain('data-module="settings">');
    expect(page.text).toContain('</svg>设定</button>');
    expect(page.text).not.toContain('</svg>设定库</button>');
    expect(page.text).toContain('data-module="outlines"');
    expect(page.text).toContain('<span class="nav-label">大纲/伏笔</span>');
    expect(page.text).toMatch(/data-module="races"[\s\S]*id="module-more-button"[\s\S]*class="module-nav-secondary hidden"[^>]*data-module="outlines"/u);
    expect(application.text).not.toContain("navButton.textContent = unresolved.length");
    expect(workPermissions.text).toContain('label: "大纲/伏笔"');
    expect(page.text).toContain('<button class="ai-analysis-entry" type="button" data-module="tasks">');
    expect(page.text).toContain('</svg>AI 分析</button>');
    expect(page.text).toContain('id="ai-assistant-entry" class="module-nav-secondary hidden ai-assistant-entry" type="button" aria-controls="ai-panel" aria-expanded="false"');
    expect(page.text).toMatch(/id="module-more-button"[\s\S]*id="ai-assistant-entry" class="module-nav-secondary hidden ai-assistant-entry"/u);
    expect(page.text).toMatch(/id="ai-assistant-entry"[^>]*><svg class="nav-icon"[^>]*><path d="M12 5\.25a3\.25/u);
    expect(page.text).toContain('</svg>创作助手</button>');
    expect(page.text).toContain('feature=ai-assistant-brain-icon-v1');
    expect(page.text).toContain('id="module-more-button"');
    expect(page.text).toContain('<span class="nav-label">更多</span>');
    expect(page.text.match(/class="module-nav-secondary hidden/gu)).toHaveLength(7);
    expect(page.text.match(/class="nav-icon"/gu)).toHaveLength(17);
    expect(page.text).toContain('data-module="ai-settings"');
    expect(page.text).toContain('data-work-settings');
    expect(page.text).toContain(">作品设置</button>");
    expect(application.text).toContain('button.hasAttribute("data-work-settings")');
    expect(application.text).toContain("openWorkSettingsDialog(work)");
    expect(application.text).toContain('$("#ai-assistant-entry").addEventListener("click"');
    expect(application.text).toContain('aiConversationWorkspaceOpen = Boolean(visible)');
    expect(application.text).toContain('panelLayout.aiCollapsed = aiConversationWorkspaceOpen ? false : mobileWorkspace;');
    expect(application.text).toContain('$("#ai-panel-toggle").textContent = aiConversationWorkspaceOpen ? "×" : (panelLayout.aiCollapsed ? "‹" : "›");');
    expect(application.text).toContain('if (isMobileViewport()) {');
    expect(application.text).toContain('tasks: ["AI 深度分析", "AI 分析中心"');
    expect(application.text).toContain('openDialog("开始 AI 分析"');
    expect(application.text).toContain('selector: "[data-module=\\"tasks\\"]"');
    expect(styles.text).toContain(".module-nav .ai-analysis-entry");
    expect(styles.text).toContain(".module-nav .ai-assistant-entry");
    expect(styles.text).not.toContain(".app-shell:not(.shelf-mode):not(.ai-workspace-mode) .ai-panel { display: none; }");
    expect(styles.text).toContain(".app-shell.ai-workspace-mode > :is(.topbar, .left-panel, .main-panel) { visibility: hidden; pointer-events: none; }");
    expect(styles.text).toContain("height: 100dvh; max-height: 100dvh;");
    expect(styles.text).toContain(".module-nav .ai-analysis-entry,\n.module-nav .ai-analysis-entry:hover,\n.module-nav .ai-analysis-entry.active { background: transparent;");
    expect(styles.text).toContain("#module-more-button { grid-column: 2;");
    expect(styles.text).toContain('.chapter-node { display: grid; grid-template-columns: minmax(0, 1fr) max-content; gap: 8px; width: calc(100% + 6px); padding: 9px 8px 9px 24px;');
    expect(styles.text).toContain('.record-markdown-preview { display: -webkit-box;');
    expect(styles.text).toContain('-webkit-line-clamp: 12;');
    expect(styles.text).toContain('.module-header-actions > [data-module-header-action] { order: 1; }');
    expect(styles.text).toContain('.module-header-actions > .module-count-badge { order: 0; }');
    expect(styles.text).toContain('.module-header-actions > #module-create-button { order: 2; min-height: 36px; }');
    expect(styles.text).toContain('.module-layout-toggle button { display: inline-grid; place-items: center; width: 36px; min-height: 34px;');
    expect(page.text).toContain('data-testid="relationship-fullscreen"');
    expect(page.text).toContain('data-testid="relationship-map-expanded"');
    expect(page.text).toContain('class="relationship-map-floating-close"');
    expect(page.text).not.toContain('id="relationship-map-dialog-title"');
    expect(page.text).toContain('data-testid="chapter-type-menu"');
    expect(application.text).toContain("async function renderOutlines(");
    expect(application.text).toContain("function setModuleNavExpanded(expanded)");
    expect(application.text).toContain('data-testid="timeline-axis"');
    expect(application.text).toContain('data-timeline-track-tab');
    expect(application.text).toContain('data-timeline-sort="asc"');
    expect(application.text).toContain('data-timeline-sort="desc"');
    expect(application.text).toContain("function openTimelineTrackDialog(item)");
    expect(styles.text).toContain(".timeline-track-tabs { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 10px; }");
    expect(styles.text).toContain(".timeline-track-menu[aria-pressed=\"true\"] { color: var(--ink);");
    expect(styles.text).toContain(".timeline-list { position: relative; margin-left: 15px; border-left: 1px solid var(--line); }");
    expect(styles.text).toContain(".timeline-item::before { content: \"\"; position: absolute; left: -5px; top: 5px;");
    expect(styles.text).not.toContain(".timeline-kanban { display: grid; grid-auto-flow: column;");
    expect(application.text).toContain("async function streamChat(requestHolder, body, idempotencyKey)");
    expect(application.text).toContain("createStreamTypewriter");
    expect(application.text).toContain("content.innerHTML = renderMarkdown(text)");
    expect(application.text).toContain('class="message-body"');
    expect(styles.text).toContain(".message-body h1, .message-body h2");
    expect(styles.text).toContain(".prompt-composer-actions { position: absolute; right: 8px; bottom: 8px;");
    expect(styles.text).toContain(".account-menu button { min-height: 30px; padding: 6px 9px; border: 1px solid var(--line);");
    expect(page.text).toContain('<strong id="account-menu-name" class="account-menu-name"><span id="account-menu-display-name">账户</span><span id="account-menu-username" class="account-menu-username">@account</span></strong>');
    expect(application.text).toContain('$("#account-menu-display-name").textContent = session.user.displayName');
    expect(application.text).toContain('$("#account-menu-username").textContent = `@${session.user.username}`');
    expect(styles.text).toContain(".account-menu { position: absolute; z-index: 80; top: 48px; right: 84px; display: grid; width: 180px; min-width: 0;");
    expect(styles.text).toContain(".account-menu-name { display: grid; min-width: 0; gap: 2px; }");
    expect(styles.text).toContain(".account-menu-name > span { overflow-wrap: anywhere; }");
    expect(styles.text).not.toContain(".account-menu-name > span { overflow: hidden;");
    expect(styles.text).toContain("font-size: 10px; }");
    expect(styles.text).toContain(".account-menu button:hover, .account-menu button:focus-visible");
    expect(styles.text).toContain(".book-info > span { overflow: hidden; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; line-height: 1.4; }");
    expect(styles.text).toContain(".book-shelf { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 24px 14px; }");
    expect(styles.text).toContain(".book-info > span, .book-access-badge { display: none; }");
    expect(styles.text).toContain("#onboarding-dialog, #onboarding-menu-button { display: none !important; }");
    expect(styles.text).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(styles.text).toContain(".topbar .work-meta { display: none; }");
    expect(styles.text).toContain(".account-button > span:last-child { display: none; }");
    expect(styles.text).toContain(".app-shell.shelf-mode #top-search-button { display: none; }");
    expect(styles.text).toContain(".app-shell.shelf-mode .mobile-module-tab { display: none; }");
    expect(styles.text).toContain(".mobile-module-tab { position: fixed;");
    expect(styles.text).toContain(".mobile-panel-backdrop { position: fixed; z-index: 36;");
    expect(styles.text).toContain(".shelf-view { height: 100%; min-height: 0; padding: 28px var(--mobile-gutter) 42px; }");
    expect(styles.text).toMatch(/\.left-panel \{[\s\S]*?z-index: 37;/);
    expect(styles.text).toContain("width: 100%;\n    grid-column: auto;");
    expect(styles.text).toContain(".ai-panel {\n    position: fixed;\n    z-index: 35;");
    expect(application.text).toContain("function isMobileViewport()");
    expect(styles.text).toContain(".presence-button #presence-count { display: none; }");
    expect(styles.text).toContain(".top-actions .save-state { display: none; }");
    expect(application.text).not.toContain("function setMobilePanel(panel, open)");
    expect(application.text).not.toContain("function isMobileLayout()");
    expect(application.text).toContain('if (isMobileViewport()) return;');
    expect(page.text).not.toContain('id="mobile-outline-toggle"');
    expect(page.text).not.toContain('id="mobile-ai-toggle"');
    expect(page.text).toContain('id="mobile-module-tab"');
    expect(styles.text).not.toContain("-webkit-box-orient: vertical; min-height: 2.8em;");
    expect(styles.text).toContain(".config-section:first-child { margin-top: 0; padding-top: 0; border-top: 0; }");
    expect(styles.text).toContain(".book-card-settings {");
    expect(styles.text).toContain("padding: 2px 6px;");
    expect(styles.text).toContain(".left-panel { display: flex; flex-direction: column; border-right: 1px solid var(--line); padding: 0; overflow: hidden; }");
    expect(styles.text).toContain(".left-panel-body { flex: 1 1 auto; min-height: 0; padding: 18px 14px 16px; overflow-y: auto; }");
    expect(styles.text).toContain(".left-panel-body { padding-inline: 10px; }");
    expect(styles.text).not.toContain(".left-panel-body { flex: 1 1 auto; min-height: 0; padding: 18px 24px 16px 14px; overflow-y: auto; scrollbar-gutter: stable; }");
    expect(page.text).toContain('class="left-panel-body"');
    expect(styles.text).toContain(".left-actions { display: block; margin: 0 0 15px; }");
    expect(styles.text).toContain(".file-button { min-height: 30px; font-size: 11px;");
    expect(styles.text).toContain(".panel-heading { display: flex; align-items: center; gap: 8px; padding: 15px 0 9px 7px;");
    expect(application.text).toContain('const stateName = sending ? "stop" : switching ? "switching" : "send";');
    expect(application.text).toContain('button.disabled = switching;');
    expect(application.text).toContain('button.classList.toggle("is-stop", sending);');
    expect(application.text).toContain('content: normalizeParagraphSpacing($("#chapter-content").value)');
    expect(application.text).toContain("collapseChapterInputBlankLines(event.currentTarget)");
    expect(application.text).toContain("function openVolumeDialog(item)");
    expect(application.text).toContain('openDialog(item ? "分卷详情" : "新建分卷"');
    expect(application.text).toContain('data-dialog-volume-export>导出 EPUB</button>');
    expect(application.text).toContain('downloadVolumeEpub(item, event.currentTarget)');
    expect(application.text).toContain('class="ghost-button volume-detail-button"');
    expect(application.text).toContain('data-volume-detail="${esc(volume.id)}"');
    expect(application.text).toContain('class="volume-detail-icon"');
    expect(application.text).toContain('title="打开“${esc(volume.title)}”分卷详情"');
    expect(application.text).toContain('button.dataset.volumeDetail));');
    expect(application.text).toContain('event.key !== "ContextMenu" && !(event.shiftKey && event.key === "F10")');
    expect(application.text).toContain('field("keywords", "分卷关键词", "keyword-chips"');
    expect(application.text).toContain('keywords: uniqueRelationshipKeywords(form.getAll("keywords").map(String))');
    expect(application.text).toContain('name="storyOrder" type="number" min="0" max="1000000" step="1" required');
    expect(application.text).toContain('id="volume-story-order-help" class="form-field-note"');
    expect(application.text).toContain('storyOrder: Number(form.get("storyOrder"))');
    expect(application.text).toContain("不改变左侧目录、阅读或导出顺序");
    expect(page.text).toContain("feature=volume-story-order-v1");
    expect(application.text).toContain('data-dialog-volume-delete');
    expect(application.text).toContain('async function deleteVolume(item)');
    expect(application.text).toContain('$("#form-dialog").close();');
    expect(application.text).toContain('body: { expectedVersionNo: item.versionNo }');
    expect(styles.text).toContain(".keyword-chip:hover button, .keyword-chip:focus-within button");
    expect(styles.text).toContain("opacity: 0; pointer-events: none; transition: opacity .15s ease");
    expect(application.text).not.toContain("data-edit-volume");
    expect(application.text).toContain('title="左键展开或折叠；右键打开分卷详情；可将章节拖到这里追加"');
    expect(application.text).toContain("const proseEditable = canEditProse();");
    expect(application.text).toContain("${proseEditable ? `<button class=\"add-button chapter-add-button\"");
    expect(application.text).toContain('class="add-button chapter-add-button"');
    expect(styles.text).toContain(".volume-detail-button { display: none; }");
    expect(styles.text).toContain(".panel-heading { display: flex; margin-top: 8px; }");
    expect(styles.text).toContain("#novel-tree { display: block; padding-bottom: 18px; }");
    expect(styles.text).toContain(".volume-detail-button { display: inline-flex; flex: 0 0 40px;");
    expect(styles.text).not.toContain(".panel-heading, #novel-tree { display: none; }");
    expect(application.text).toContain('aria-label="在“${esc(volume.title)}”中新建章节"');
    expect(application.text).toContain('button.dataset.volumeToggle));');
    expect(application.text).toContain('class="record-card character-card preview-record-card has-card-edit" data-open-character');
    expect(application.text).toContain('class="character-lock-badge"');
    expect(application.text).toContain('class="record-card module-row character-row character-card preview-record-card"');
    expect(styles.text).toContain(".character-row { grid-template-columns: minmax(140px, .28fr) minmax(0, 1fr) auto; }");
    expect(application.text).toContain("所属组织");
    expect(application.text).toContain('card.addEventListener("keydown"');
    expect(page.text).toContain('data-module="races"');
    expect(application.text).toContain("async function renderRaces(");
    expect(application.text).toContain("async function openRaceDialog(item, options)");
    expect(application.text).toContain('field("parentRaceId", "父种族", "select"');
    expect(application.text).toContain('class="race-tree-node"${state.collapsedRaceIds.has(item.id) ? "" : " open"}');
    expect(application.text).toContain("collapsedRaceIds: new Set()");
    expect(application.text).toContain("function bindRaceTreeNodeToggles()");
    expect(application.text).toContain("function syncRaceTreeExpandToggle()");
    expect(application.text).toContain("state.collapsedRaceIds.clear()");
    expect(application.text).toContain('data-race-tree-expand="${action}"');
    expect(application.text).toContain("function setAllRaceTreeNodesOpen(open)");
    expect(application.text).toContain('field("raceId", "种族", "select"');
    expect(application.text).not.toContain('field("species", "种族", "text"');
    expect(application.text).toContain('field("memberIds", isRace ? "属于该种族的角色（可多选）" : "组织成员（可多选）", "chips"');
    expect(application.text).toContain('field("organizationIds", "所属组织（可多选）", "chips"');
    expect(application.text).toContain('input.setAttribute("aria-label", rows.dataset.label || "列表项目")');
    expect(application.text).toContain('Number(chapter.wordCount ?? 0).toLocaleString("zh-CN")}</small>');
    expect(application.text).toContain('Number(state.work.wordCount ?? 0).toLocaleString("zh-CN")');
    expect(application.text).toContain('Number(work.wordCount ?? 0).toLocaleString("zh-CN")');
    expect(application.text).toContain('<span>${Number(volume.chapterCount ?? chapters.length)} 章</span>');
    expect(application.text).toContain("function renderKnowledgeMarkdownSections()");
    expect(application.text).toContain("data-knowledge-section-create");
    expect(application.text).toContain("function openKnowledgeSectionEditor");
    expect(application.text).toContain('data.getAll("memberIds")');
    expect(styles.text).toContain(".chip-picker { display: flex; flex-wrap: wrap;");
    expect(styles.text).toContain(".relationship-map-expanded-host .relationship-map-toolbar { padding-right: 72px; }");
    expect(styles.text).toContain(".relationship-map-expanded-host .relationship-mindmap { flex: 1 1 auto; height: auto; min-height: 0; }");
    expect(application.text).toContain('field("protocol", "接口协议", "select", protocol');
    expect(application.text).toContain('api("/api/platform/ai/protocols")');
    expect(application.text).toContain('const providerProtocolFieldOptions = protocolOptions.map((option) => [option.value, option.label])');
    expect(application.text).toContain('name="useMaxCompletionTokens"');
    expect(application.text).toContain('maxTokensParameter: form.get("useMaxCompletionTokens") === "on" ? "max_completion_tokens" : "max_tokens"');
    expect(application.text).toContain('name="useAdaptiveThinking"');
    expect(application.text).toContain('thinkingType: form.get("useAdaptiveThinking") === "on" ? "adaptive" : "enabled"');
    expect(application.text).toContain("思考类型（开启时）");
    expect(application.text).toContain('name="analysisTimeoutSeconds"');
    expect(application.text).toContain('analysisTimeoutSeconds: Number(form.get("analysisTimeoutSeconds"))');
    expect(application.text).toContain("用于全书分析和关系分析的单次非流式请求");
    expect(application.text).toContain('const supportsMaxCompletionTokens = selectedProtocolOption(protocolSelect.value)?.supportsMaxCompletionTokens !== false');
    expect(application.text).toContain('maxTokensParameterFieldElement.hidden = !supportsMaxCompletionTokens');
    expect(application.text).toContain('maxTokensParameterFieldElement.classList.toggle("hidden", !supportsMaxCompletionTokens)');
    expect(application.text).toContain('最大输出参数：${esc(provider.maxTokensParameter ?? "max_tokens")}');
    expect(application.text).toContain('思考类型：${esc(provider.thinkingType ?? "enabled")}');
    expect(application.text).toContain('分析请求超时：${Number(provider.analysisTimeoutSeconds ?? DEFAULT_AI_ANALYSIS_TIMEOUT_SECONDS).toLocaleString("zh-CN")} 秒');
    expect(application.text).not.toContain('field("maxTokens", "最大输出令牌数", "number", item?.maxTokens ?? 32000)');
    expect(application.text).toContain('item && item.providerStatus === "enabled"');
    expect(application.text).toContain('class="model-connection-test"');
    expect(application.text).toContain('supportsMultimodalModelProtocol(provider?.protocol, protocolOptions)');
    expect(application.text).toContain('data-test-model="${esc(item.id)}"');
    expect(application.text).toContain('provider.status === "enabled" ? `<button data-test-provider=');
    expect(application.text).not.toContain("model-test-button");
    expect(application.text).toContain("providerModels.length");
    expect(application.text).toContain("function isSelectableModel(model)");
    expect(application.text).toContain("provider-disabled-notice");
    expect(application.text).toContain("已停用模型不会出现在新任务选择中");
    expect(application.text).not.toContain('<span class="model-status-badge is-disabled">供应商已停用</span>');
    expect(styles.text).toContain(".provider-card.is-disabled");
    expect(styles.text).toContain(".provider-status-badge.is-disabled");
    expect(styles.text).toContain(".model-connection-test");
    expect(styles.text).toContain(".model-temperature-hint, .model-context-window-hint");
    expect(application.text).toContain('id="model-context-window"');
    expect(application.text).toContain('min="${MIN_MODEL_CONTEXT_WINDOW}"');
    expect(application.text).toContain("低于 128K 的模型在小说创作场景不太适用，建议使用支持更长上下文的模型。");
    expect(application.text).toContain('contextWindowInput.setCustomValidity(guidance.belowMinimum ? "模型上下文不能低于 32K（32768 Token）。" : "")');
    expect(application.text).toContain("contextWindowHint.hidden = !guidance.showRecommendation");
    expect(application.text).toContain('field("maxTokens", "默认最大输出令牌数", "number", values.maxTokens)');
    expect(application.text).toContain('Kimi 模型必须设置温度为 1。');
    expect(application.text).toContain('field("thinkingEnabled", "开启思考模式（供应商需支持相应参数）", "checkbox", values.thinkingEnabled)');
    expect(application.text).toContain('field("thinkingEffort", "思考强度（模型默认时不发送强度参数）", "select", values.thinkingEffort, MODEL_THINKING_EFFORT_OPTIONS)');
    expect(application.text).toContain('thinkingEffort: form.get("thinkingEffort")');
    expect(application.text).toContain('thinkingEffortSelect.disabled = !thinkingEnabledInput.checked');
    expect(application.text).toContain("所有请求都会携带最大输出令牌数，默认值为 32000。");
    expect(application.text).not.toContain("所有请求都会携带 max_tokens");
    expect(modelConfig.text).toContain("contextWindow: model?.contextWindow ?? 128000");
    expect(modelConfig.text).toContain("thinkingEnabled: model?.thinkingEnabled ?? true");
    expect(modelConfig.text).toContain('thinkingEffort: modelThinkingEfforts.has(model?.thinkingEffort) ? model.thinkingEffort : "default"');
    expect(modelConfig.text).toContain('["auto", "自动（auto）"]');
    expect(modelConfig.text).toContain('["low", "低（low）"]');
    expect(modelConfig.text).toContain('["medium", "中（medium）"]');
    expect(modelConfig.text).toContain('["high", "高（high）"]');
    expect(modelConfig.text).toContain('["xhigh", "超高（xhigh）"]');
    expect(modelConfig.text).toContain('["max", "最高（max）"]');
    expect(modelConfig.text).toContain("maxTokens: model?.preset?.max_tokens ?? 32000");
    expect(application.text).toContain('async function renderPlatformAiConfig()');
    expect(application.text).toContain('async function renderBookAiSettings()');
    expect(application.text).toContain('id="agent-tool-call-limit"');
    expect(application.text).toContain("settings.agentToolCallLimitMaximum");
    expect(application.text).toContain("Agent 工具调用上限不能超过 ${maximum} 次");
    expect(styles.text).toContain(".config-inline-save .book-summary-context-percent-field,");
    expect(styles.text).toContain("grid-template-columns: minmax(110px, 130px) 88px");
    expect(styles.text).toContain(".config-inline-save .context-compact-threshold-field { grid-template-columns: minmax(0, 1fr)");
    expect(styles.text).toContain(".config-inline-save > .config-checkbox-field { display: inline-flex !important; align-items: center; gap: 8px; min-height: 32px; margin: 0; color: var(--muted); font-size: calc(11px * var(--ui-font-scale));");
    expect(styles.text).toContain(".ai-agent-tools-section + .empty-state { margin-top: 24px; border-top: 1px solid var(--line); }");
    expect(application.text).toContain('id="agent-tool-call-global-multiplier"');
    expect(application.text).toContain('class="settings-layout-toggle agent-tool-call-global-multiplier-toggle"');
    expect(application.text).toContain('Agent 工具调用上限');
    expect(application.text).toContain('不会因 Compact 重置的熔断阀');
    expect(application.text).toContain('href="https://scriverse.top/docs/global-tool-call-limit.html"');
    expect(application.text).toContain('了解原理与推荐设置');
    expect(application.text).not.toContain("ai-context-usage");
    expect(application.text).toContain("setAiChatTabContextUsage(tab, payload.contextUsage)");
    expect(application.text).toContain('addEventListener("contextmenu"');
    expect(application.text).toContain("collapsedVolumeIds");
    expect(application.text).toContain('data-testid="continuation-guard"');
    expect(graph.text).toContain("export function buildRelationshipGraph");
    expect(graph.text).toContain("export function formatRelationshipLabel");
    expect(graph.text).toContain("export function groupRelationshipDetailsByCharacterName");
    expect(graph.text).toContain("export function layoutRelationshipNetwork");
    expect(graph.text).toContain('viewport.dataset.testid = "relationship-network"');
    expect(graph.text).toContain('viewport.dataset.interaction = "dragging"');
    expect(graph.text).toContain("highlightedKeywords.push(fullLabel)");
    expect(graph.text).toContain("const label = fullLabel.length > 42");
    expect(graph.text).toContain("export function createGalaxyRenderer");
    expect(graph.text).toContain("export function normalizeGalaxyFrameRate");
    expect(graph.text).toContain("export function createGalaxyStarfield");
    expect(graph.text).toContain("export function projectGalaxyPoint");
    expect(graph.text).toContain("export function getGalaxyNodeFocusCamera");
    expect(graph.text).toContain("export function getGalaxyNodeLabelOffset");
    expect(graph.text).toContain('element.style.setProperty("--node-marker-scale"');
    expect(graph.text).toContain("focusCameraOnNode(node)");
    expect(graph.text).toContain('shell.dataset.resourceState = "released"');
    expect(graph.text).toContain("target.width = 1");
    expect(graph.text).toContain("stars.length = 0");
    expect(application.text).toContain("if (state.galaxy === galaxy) state.galaxy = null");
    expect(application.text).toContain("frameRate: state.uiSettings.galaxyFrameRate");
    expect(graph.text).toContain("export function getRelationshipNodeFocusView");
    expect(graph.text).toContain("focusViewOnNode(node.id)");
    expect(graph.text).toContain("export function shouldShowRelationshipNodeLabel");
    expect(graph.text).toContain("export function getRelationshipNodeLabelFontSize");
    expect(graph.text).toContain("duration: 650");
    expect(graph.text).toContain('shell.dataset.sceneDimension = "3"');
    expect(graph.text).toContain("export const GALAXY_ROTATION_RADIANS_PER_MS = 0.000012");
    expect(graph.text).toContain("camera.yaw += elapsed * GALAXY_ROTATION_RADIANS_PER_MS");
    expect(page.text).toContain('data-testid="galaxy-3d-starfield"');
    expect(page.text).toContain('data-testid="galaxy-3d-relationships"');
    expect(page.text).toContain('data-testid="galaxy-grid"');
    expect(page.text).toContain('aria-pressed="false" data-testid="galaxy-grid">显示空间网格');
    expect(graph.text).toContain('expand.dataset.testid = "relationship-map-expand"');
    expect(graph.text).toContain("viewport.dataset.draggedNodeId = node.id");
    expect(graph.text).toContain("viewport.dataset.graphScale = viewScale.toFixed(3)");
    expect(graph.text).toContain("expanded: Object.freeze({ width: 1600, height: 900");
    expect(graph.text).toContain("repulsionStrength: 22800");
    expect(graph.text).toContain("viewport.dataset.layoutWidth = String(layout.width)");
    expect(graph.text).toContain('edgeDetail.className = "mind-edge-detail hidden"');
    expect(styles.text).toContain(".mind-edge-detail { position: absolute;");
    expect(graph.text).toContain('viewport.addEventListener("wheel"');
    expect(graph.text).toContain('button.addEventListener("pointermove"');
    expect(graph.text).toContain("shell.dataset.draggedNodeId = node.id");
    expect(graph.text).toContain("getGalaxyNodeSize(node, maxDegree, layout.nodes.length, appearance.sizeScale)");
    expect(graph.text).toContain("export function getGalaxyNodeAppearance");
    expect(graph.text).toContain('button.dataset.relationshipTier = appearance.tier');
    expect(graph.text).toContain('button.dataset.celestialType = appearance.celestialType');
    expect(graph.text).not.toContain('button.title = `${node.degree} 条关系');
    expect(graph.text).toContain('button.style.setProperty("--node-color", appearance.color)');
    expect(graph.text).toContain("getGalaxyNodeDepthOpacity(point.depth)");
    expect(graph.text).toContain("initialNodePositions");
    expect(styles.text).toContain(".book-shelf");
    expect(styles.text).toContain(".galaxy-dialog");
    expect(styles.text).toMatch(/\.galaxy-controls \{[^}]*width: 104px;/u);
    expect(styles.text).toContain(".galaxy-shell.is-rotating-camera");
    expect(styles.text).toContain("grid-template-rows: var(--node-size) auto");
    expect(styles.text).toContain("--node-color");
    expect(styles.text).toContain("--node-brightness");
    expect(styles.text).toContain('[data-celestial-type="ringed"]');
    expect(application.text).not.toContain('id="create-character-audit-task"');
    expect(application.text).toContain('character-identity-audit');
    expect(application.text).toContain("data-merge-review");
    expect(application.text).toContain("data-keep-characters-separate");
    expect(styles.text).toContain(".character-duplicate-pair");
  });

  it("从导入作品到采纳续写、抽取时间轴并安全导出", async () => {
    await request(runtime.app).get("/api/health").expect(200);
    const page = await request(runtime.app).get("/").expect(200).expect("Content-Type", /html/u);
    expect(page.headers["x-frame-options"]).toBe("DENY");
    expect(page.headers["content-security-policy"]).toContain("frame-ancestors 'none'");
    expect(page.headers["content-security-policy"]).toContain("img-src 'self' data: blob:;");

    const work = await request(runtime.app).post("/api/works").send({ title: "星际纪元", author: "作者" }).expect(201);
    const workId = work.body.data.id;
    const imported = await request(runtime.app).post(`/api/works/${workId}/import`)
      .attach("file", Buffer.from("第一卷 启航\n第一章 北港\n飞船停在北港。林舟检查跃迁引擎。林舟想起沈星的警告。\n第二章 旧信\n沈星仍保存着林舟的旧信。"), "星际纪元.txt")
      .expect(201);
    expect(JSON.stringify(imported.body)).not.toContain("飞船停在北港。");
    const directory = await request(runtime.app).get(`/api/works/${workId}`).expect(200);
    const chapterId = directory.body.data.volumes[0].chapters[0].id;

    await request(runtime.app).post(`/api/works/${workId}/settings`).send({
      title: "跃迁冷却规则",
      category: "世界规则",
      content: "飞船每次跃迁后必须冷却十二小时。",
      status: "confirmed",
      locked: true
    }).expect(201);
    await request(runtime.app).post(`/api/works/${workId}/characters`).send({
      name: "林舟",
      attributes: { species: "人类" },
      currentState: { location: "北港" },
      lockedFields: ["species", "location"]
    }).expect(201);
    await request(runtime.app).post(`/api/works/${workId}/characters`).send({
      name: "沈星",
      aliases: ["沈博士"],
      currentState: { location: "主星" }
    }).expect(201);

    const provider = await request(runtime.app).post(`/api/works/${workId}/providers`).send({
      name: "系统测试模型服务",
      baseUrl,
      apiKey: "sk-system-test-secret",
      status: "enabled"
    }).expect(201);
    await request(runtime.app).post(`/api/providers/${provider.body.data.id}/test`).send({}).expect(200);
    const model = await request(runtime.app).post(`/api/providers/${provider.body.data.id}/models`).send({
      displayName: "长篇创作模型",
      modelId: "system-novel-model",
      purposes: ["创作续写", "时间轴分析"]
    }).expect(201);

    const streamed = await request(runtime.app).post(`/api/works/${workId}/chat/stream`).send({
      instruction: "用一句话描述离港",
      scope: { type: "chapter", chapterId },
      modelId: model.body.data.id
    }).expect(200).expect("Content-Type", /text\/event-stream/u);
    expect(streamed.text).toContain('event: delta\ndata: {"delta":"舱门关闭，"}');
    expect(streamed.text).toContain('event: delta\ndata: {"delta":"飞船离开北港。"}');
    expect(streamed.text.indexOf('"delta":"舱门关闭，"')).toBeLessThan(streamed.text.indexOf('"delta":"飞船离开北港。"'));
    expect(streamed.text).toContain("event: complete");

    const suggestion = await request(runtime.app).post(`/api/works/${workId}/suggestions`).send({
      taskType: "continue",
      instruction: "续写离港场景，不能让飞船立即再次跃迁。",
      scope: { type: "chapter", chapterId },
      modelId: model.body.data.id
    }).expect(201);
    const beforeAccept = await request(runtime.app).get(`/api/chapters/${chapterId}`).expect(200);
    expect(beforeAccept.body.data.versionNo).toBe(1);
    expect(beforeAccept.body.data.content).not.toContain("舱门关闭");

    const accepted = await request(runtime.app).post(`/api/suggestions/${suggestion.body.data.id}/accept`).send({}).expect(200);
    expect(accepted.body.data.chapter.versionNo).toBe(2);
    expect(accepted.body.data.chapter.content).toContain("舱门关闭");

    const timelineTask = await request(runtime.app).post(`/api/works/${workId}/tasks`).send({
      taskType: "timeline-analysis",
      scope: { type: "book" }
    }).expect(201);
    const completedTask = await request(runtime.app).post(`/api/tasks/${timelineTask.body.data.id}/run`).send({ modelId: model.body.data.id }).expect(200);
    expect(completedTask.body.data).toMatchObject({ status: "review", progress: 100 });
    expect(completedTask.body.data.result.candidateCount).toBe(1);

    const timeline = await request(runtime.app).get(`/api/works/${workId}/timeline`).expect(200);
    expect(timeline.body.data[0]).toMatchObject({ name: "北港启航", status: "candidate" });

    const relationshipTask = await request(runtime.app).post(`/api/works/${workId}/tasks`).send({
      taskType: "relationship-analysis",
      scope: { type: "book" }
    }).expect(201);
    const relationshipResult = await request(runtime.app).post(`/api/tasks/${relationshipTask.body.data.id}/run`).send({ modelId: model.body.data.id }).expect(200);
    expect(relationshipResult.body.data.result.candidateCount).toBe(1);
    const relationships = await request(runtime.app).get(`/api/works/${workId}/relationships`).expect(200);
    expect(relationships.body.data[0]).toMatchObject({ category: "social", subtype: "朋友", confidence: 0.82, confirmationStatus: "pending" });
    expect(relationships.body.data[0].evidence).toHaveLength(2);

    const search = await request(runtime.app).get(`/api/works/${workId}/search?q=${encodeURIComponent("北港")}`).expect(200);
    expect(search.body.data.some((item: { type: string }) => item.type === "chapter")).toBe(true);

    const exported = await request(runtime.app).get(`/api/works/${workId}/export?format=json`).expect(200);
    const serialized = JSON.stringify(exported.body);
    expect(serialized).toContain("北港启航");
    expect(serialized).not.toContain("sk-system-test-secret");
    expect(serialized).not.toContain("encrypted_key");

    const modelRequest = receivedBodies.find((body) => JSON.stringify(body).includes("续写离港场景"));
    expect(JSON.stringify(modelRequest)).toContain("飞船每次跃迁后必须冷却十二小时");
    expect(JSON.stringify(modelRequest)).toContain("species=人类");
  }, 20_000);
});
