import request from "supertest";
import { afterEach, describe, expect, it } from "vitest";
import { createRuntime, type Runtime } from "../../src/app.js";

describe("编辑器工具栏布局", () => {
  const runtimes: Runtime[] = [];

  afterEach(async () => {
    while (runtimes.length) await runtimes.pop()?.close();
  });

  it("让章节路径独占首行，并统一侧栏工具按钮尺寸", async () => {
    const runtime = createRuntime({
      databasePath: ":memory:",
      masterSecret: "editor-toolbar-layout-system-test-secret",
      disableUserAuth: true,
      serveUi: true
    });
    runtimes.push(runtime);

    const page = await request(runtime.app).get("/").expect(200);
    const styles = await request(runtime.app).get("/styles.css").expect(200);
    const application = await request(runtime.app).get("/app.js").expect(200);

    expect(page.text).toContain('<span id="chapter-path" class="eyebrow">未选择章节</span>\n            <input id="chapter-title"');
    expect(page.text).toContain('id="chapter-edit-button" class="primary-button hidden"');
    expect(page.text).toContain('id="chapter-annotations-button"');
    expect(page.text).toContain('id="chapter-annotations-dialog"');
    expect(page.text).toContain('class="module-nav-secondary hidden" type="button" data-module="comments"');
    expect(page.text).toContain('<span class="nav-label">正文评论</span>');
    expect(page.text).toContain('id="add-line-annotation"');
    expect(page.text).toContain('id="add-line-annotation" type="button" role="menuitem">添加评论</button>');
    expect(page.text).toContain('id="add-line-todo"');
    expect(page.text).toContain('&feature=annotation-precise-locate-v1');
    expect(page.text).toMatch(/styles\.css\?[^"\n]*feature=markdown-word-count-five-digit-v2/u);
    expect(page.text).toMatch(/styles\.css\?[^"\n]*feature=annotation-marker-offset-v1/u);
    expect(application.text).toContain("async function createSelectedLineAnnotation(");
    expect(application.text).toContain("function chapterAnnotationCard(");
    expect(application.text).toContain("function bindChapterAnnotationCards(");
    expect(application.text).toContain("function renderChapterAnnotations(");
    expect(application.text).toContain("function revealChapterLines(startLine, endLine)");
    expect(application.text).toContain("revealChapterLines(annotation.startLine, annotation.endLine);");
    expect(application.text).toContain("/annotation-counts");
    expect(application.text).toContain("lineAnnotationCount");
    expect(application.text).toContain("?line=${encodeURIComponent(line)}");
    expect(application.text).toContain("async function renderWorkChapterComments(");
    expect(application.text).toContain('/chapter-annotations`');
    expect(application.text).toContain('renderModulePagination(pageResult, "comments", "正文评论与待办列表")');
    expect(application.text).toContain('$("#chapter-content").addEventListener("contextmenu"');
    expect(application.text).toContain("value: annotation.note");
    expect(application.text).toContain('"解决评论"');
    expect(application.text).toContain('"删除评论"');
    expect(styles.text).toContain(".chapter-annotation-card");
    expect(styles.text).toContain(".chapter-comment-module-list");
    expect(styles.text).toContain(".chapter-annotation-source");
    expect(styles.text).toContain(".chapter-line-annotation-count { position: absolute; top: -4px; right: -10px;");
    expect(styles.text).toContain("font-family: var(--font-mono), monospace; font-size: 10px; line-height: 1.6");
    expect(page.text).toContain(">编辑</button>");
    expect(styles.text).toContain('grid-template-areas: "path path" "title actions"');
    expect(styles.text).toContain('background: transparent; font-size: 25px; padding: 0;');
    expect(styles.text).toContain('.editor-actions { grid-area: actions; display: flex; align-items: center; gap: 8px; }');
    expect(styles.text).toContain('.editor-view .editor-actions > button { min-height: 32px; padding: 6px 10px; font-size: 11px; }');
    expect(styles.text).toContain(".editor-view.is-read-only #tidy-blank-lines-button");
    expect(styles.text).toContain(".editor-view.is-read-only #save-button");
    expect(application.text).toContain("function applyChapterEditorMode()");
    expect(application.text).toContain("function enterChapterEditMode()");
    expect(application.text).toContain('persistentToast("正在保存中")');
    expect(application.text).toContain('toast(`保存成功（正文 v${saved.versionNo}）`)');
    expect(application.text).toContain('$("#chapter-delete-button").classList.toggle("hidden", permissionBlocked || chapterEditorReadOnly || !state.chapter);');
    expect(application.text).toContain('$("#chapter-edit-button").addEventListener("click", enterChapterEditMode)');
    expect(styles.text).toContain('#chapter-path { grid-area: path;');
    expect(styles.text).toContain('.file-button, .add-button { display: grid; place-items: center;');
    expect(page.text).toContain('id="new-volume-button" class="add-button"');
    expect(page.text).toContain('id="chapter-batch-dialog"');
    expect(page.text).toContain('id="chapter-batch-button" class="chapter-batch-button" type="button" aria-label="批量管理章节" title="批量管理章节"><svg');
    expect(styles.text).toContain(".chapter-batch-button svg");
    expect(application.text).toContain("async function submitChapterBatch(");
    expect(application.text).toContain("批量删除需要再次确认");
    expect(styles.text).toContain(".chapter-batch-controls");
    expect(styles.text).toContain(".chapter-batch-controls select {");
    expect(styles.text).toContain(".chapter-batch-controls select:focus-visible");
    expect(page.text).toContain('id="chapter-batch-search" type="search"');
    expect(page.text).toContain('id="chapter-batch-search-count"');
    expect(styles.text).toContain(".chapter-batch-search-field input");
    expect(application.text).toContain('$("#chapter-batch-search").addEventListener("input", renderChapterBatchDialog)');
    expect(application.text).toContain('chapters.filter((chapter) => chapter.title.toLocaleLowerCase("zh-CN").includes(searchQuery))');
    expect(page.text).not.toContain('id="new-chapter-button"');
    expect(application.text).toContain('data-new-chapter-volume');
    expect(application.text).toContain('async function openChapterDialog(volumeId = null)');
    expect(application.text).toContain('draggable="${proseEditable ? "true" : "false"}"');
    expect(application.text).toContain("async function moveChapterInTree(");
    expect(application.text).toContain("async function moveChapterByKeyboard(");
    expect(application.text).toContain('event.altKey');
    expect(styles.text).toContain('.chapter-node.is-drag-over');
    expect(page.text).toContain('<label id="import-file-button" class="file-button" aria-label="导入 TXT / DOCX">');
    expect(page.text).toContain('<span class="import-file-label import-file-label-full" aria-hidden="true">导入 TXT / DOCX</span>');
    expect(page.text).toContain('<span class="import-file-label import-file-label-compact" aria-hidden="true">导入TXT/DOCX</span>');
    expect(page.text).toContain('<span class="import-file-label import-file-label-short" aria-hidden="true">导入</span>');
    expect(page.text).not.toContain('id="import-history-button"');
    expect(page.text).toContain('id="import-history-dialog"');
    expect(page.text).toContain("大纲、伏笔、首次登场等章节关联信息不在快照中");
    expect(page.text).toContain('id="import-mode-dialog"');
    expect(page.text).toContain('id="import-mode-append"');
    expect(page.text).toContain('id="import-mode-overwrite"');
    expect(page.text).toContain('name="importMode" value="append"');
    expect(page.text).toContain('id="import-mode-confirm"');
    expect(page.text).toContain('value="confirm" type="submit" disabled>确认</button>');
    expect(page.text).toContain("把新文件解析出的卷章添加到目录末尾");
    expect(page.text).toContain("覆盖会影响章节关联资料，需要所有受影响模块均为可编辑");
    expect(styles.text).toContain(".import-mode-options");
    expect(styles.text).toContain(".import-mode-option input:checked + .import-mode-option-card");
    expect(application.text).toContain("function confirmToast(message");
    expect(application.text).toContain("当前选项：覆盖正文");
    expect(styles.text).toContain(".import-history-load-more");
    expect(application.text).toContain('$("#import-file-button").setAttribute("aria-disabled", String(proseReadOnly));');
    expect(application.text).toContain('$("#import-file-button").addEventListener("click", (event) => {');
    expect(application.text).toContain('$("#import-file").disabled = proseReadOnly;');
    expect(application.text).toContain('toast("当前权限只能编辑设定资料，不能导入正文", "error");');
    expect(styles.text).not.toContain('.prose-read-only-mode:not(.shelf-mode) .left-primary-actions .file-button');
    expect(styles.text).not.toContain('.view-only-mode:not(.shelf-mode) .left-primary-actions .file-button');
    expect(application.text).toContain('$("#import-mode-overwrite").disabled = !canOverwrite;');
    expect(application.text).toContain("function canReplaceProse(work = state.work)");
    expect(application.text).toContain("正文导入历史");
    expect(page.text).toContain('id="chapter-recycle-bin-dialog"');
    expect(application.text).toContain("正文回收站");
    expect(application.text).toContain("async function openChapterRecycleBin()");
    expect(application.text).toContain("data-restore-deleted-chapter");
    expect(application.text).toContain("data-purge-deleted-chapter");
    expect(application.text).toContain("彻底删除章节");
    expect(application.text).toContain("/permanent`");
    expect(application.text).toContain('/recycle-bin`');
    expect(application.text).toContain('$("#form-dialog").close();');
    expect(application.text).toContain("resetWorkScopedUiCaches();");
    expect(application.text).toContain("if (state.dirty) scheduleChapterAutoSave();");
    expect(application.text).toContain('apiPage(`/api/works/${encodeURIComponent(workId)}/file-versions`, page, pageSizeFor("fileVersions"))');
    expect(styles.text).toContain('@container (max-width: 120px)');
    expect(styles.text).toContain('@container (max-width: 88px)');
    expect(styles.text).toContain('@container editor-workspace (max-width: 720px)');
    expect(styles.text).toContain('.editor-toolbar { grid-template-areas: "path" "title" "actions";');
    expect(styles.text).toContain('.chapter-title { min-height: 36px; }');
    expect(styles.text).toContain('.chapter-title { font-size: 21px; }');
    expect(styles.text).toContain('.editor-view .editor-actions > button { min-width: 0; min-height: 34px; padding-inline: 6px; font-size: 11px; }');
    expect(styles.text).toContain('.vditor-editor-host .vditor-toolbar { display: flex; align-items: center; flex: 0 0 auto; }');
    expect(styles.text).toContain('.markdown-word-count { display: inline-flex; align-items: center; align-self: center; min-height: 28px; margin-left: 24px;');
    expect(styles.text).toContain('.markdown-word-count-value { display: inline-block; min-width: 6ch; font-variant-numeric: tabular-nums; text-align: right; }');
    expect(styles.text).toContain('.vditor-editor-host .vditor-line-numbers { display: none; position: absolute;');
    expect(styles.text).toContain('.vditor-editor-host .vditor-line-numbers { display: none; position: absolute; z-index: 1; inset: 0 auto 0 0; width: 42px; padding: 0; overflow: hidden; border-right: 1px solid var(--line); background: color-mix(in srgb, var(--surface-soft) 88%, transparent); color: var(--muted); font: 12px/1.75 var(--font-latin), monospace; text-align: center;');
    expect(styles.text).toContain('.vditor-editor-host.vditor.show-line-numbers .vditor-line-numbers { display: block; }');
    expect(styles.text).toContain('.vditor-editor-host .vditor-line-number { position: absolute;');
    expect(styles.text).toContain('.vditor-editor-host .vditor-line-number { position: absolute; top: 0; right: 0; left: 0; display: block; box-sizing: border-box; overflow: hidden; padding: 0; text-align: center;');
    expect(styles.text).not.toContain('.vditor-editor-host.vditor.show-line-numbers .vditor-ir,');
    expect(styles.text).not.toContain('.vditor-editor-host.vditor.show-line-numbers .vditor-wysiwyg,');
    expect(styles.text).toContain('.vditor-editor-host.vditor.show-line-numbers .vditor-sv, .vditor-editor-host.vditor.show-line-numbers .vditor-sv textarea { padding-left: 42px; }');
    expect(application.text).toContain('name: "line-number"');
    expect(application.text).toContain('function toggleVditorLineNumbers(editor)');
    expect(application.text).toContain('function updateVditorLineNumbers(editor, markdown)');
    expect(application.text).toContain('data-markdown-word-count-value');
    expect(application.text).toContain('unit.textContent = " 字";');
    expect(application.text).toContain('function collectVditorVisualLineRects(surface)');
    expect(application.text).toContain('buildVditorLineNumberRows');
    expect(styles.text).toContain('.chapter-stats { display: none; }');
    expect(styles.text).toContain('.editor-actions { position: static; z-index: auto;');
    expect(styles.text).toContain('.app-shell.left-panel-collapsed .editor-actions { transform: none; pointer-events: auto; }');
    expect(styles.text).toContain('grid-row: 2 / -1;');
    expect(styles.text).not.toContain('bottom: calc(76px + env(safe-area-inset-bottom));');
    expect(styles.text).toContain('#left-panel-toggle { flex: 0 0 30px; width: 30px; height: 30px; }');
    expect(styles.text).toContain('.ai-heading #ai-panel-toggle { flex-basis: 30px; width: 30px; min-width: 30px; min-height: 30px; height: 30px; }');
  });
});
