import request from "supertest";
import { afterEach, describe, expect, it } from "vitest";
import { createRuntime, type Runtime } from "../../src/app.js";

describe("全局 IM 工作区界面", () => {
  let runtime: Runtime;

  afterEach(async () => {
    await runtime?.close();
  });

  it("提供全局入口、三栏工作区、模型设置和 typed mention composer", async () => {
    runtime = createRuntime({
      databasePath: ":memory:",
      masterSecret: "im-ui-system-test-master-secret-with-enough-length",
      disableUserAuth: true,
      serveUi: true
    });
    const [page, application, im, styles] = await Promise.all([
      request(runtime.app).get("/").expect(200),
      request(runtime.app).get("/app.js").expect(200),
      request(runtime.app).get("/im.js").expect(200),
      request(runtime.app).get("/styles.css").expect(200)
    ]);

    expect(page.text).toContain('id="im-open-button"');
    expect(page.text).toContain('id="im-settings-button" class="im-icon-button im-settings-icon-button"');
    expect(page.text).toContain('id="im-settings-button" class="im-icon-button im-settings-icon-button" type="button" aria-label="IM 设置" title="IM 设置"><svg class="settings-icon"');
    expect(page.text).toContain('id="im-view" class="im-view hidden"');
    expect(page.text).toContain('id="im-view" class="im-view hidden" aria-label="IM 工作区"');
    expect(page.text).toContain('class="im-create-action-buttons"');
    expect(page.text).not.toContain('id="im-workspace-title"');
    expect(page.text).not.toContain('class="im-sidebar-header"');
    expect(page.text).toContain('id="im-conversation-list"');
    expect(page.text).toContain('id="im-message-feed"');
    expect(page.text).toContain('id="im-details"');
    expect(page.text).toContain('id="im-settings-dialog"');
    expect(page.text).toContain("每个模型最大失败次数");
    expect(page.text).toContain("主模型最多请求 3 次；全部失败后 fallback 再最多请求 3 次");
    expect(page.text).toContain('id="im-group-dialog"');
    expect(page.text).toContain('id="im-announcement-button"');
    expect(page.text).toContain('id="im-announcement-dialog"');
    expect(page.text).toContain('id="im-announcement-form"');
    expect(page.text).toContain('id="im-member-add-dialog"');
    expect(page.text).toContain('id="im-member-add-work"');
    expect(page.text).toContain('id="im-member-add-character-search"');
    expect(page.text).toContain('id="im-member-add-human-search"');
    expect(page.text).toContain("公告将作为一次性旁白进入所有当前 AI 角色的后续上下文，不会触发 AI 回复");
    expect(page.text).toContain('id="im-new-conversation"');
    expect(page.text).toContain('class="im-new-conversation-full">新建会话</span><span class="im-new-conversation-compact" aria-hidden="true">+</span>');
    expect(page.text).toContain('id="im-conversations-resize" class="im-conversations-resize-handle" role="separator"');
    expect(page.text).toContain('aria-label="调整 IM 会话列表宽度"');
    expect(page.text).toContain('id="im-create-work"');
    expect(page.text).toContain('id="im-create-search"');
    expect(page.text).toContain('id="im-create-selected"');
    expect(page.text).toContain('id="im-create-submit"');
    expect(page.text).toContain('id="im-send" class="im-send-button"');
    expect(page.text).toContain('id="im-composer-resize" class="im-composer-resize-handle" role="separator"');
    expect(page.text).toContain('aria-label="调整消息编辑区域高度"');
    expect(page.text).toContain('aria-label="发送消息" title="发送消息"');
    expect(page.text).toContain('M21 3 9.5 14.5M21 3l-7 18-4.5-6.5L3 10l18-7Z');
    expect(page.text).toContain("单选角色创建单聊，多选角色创建群聊");
    expect(page.text).not.toContain('id="im-direct-character"');
    expect(page.text).not.toContain('id="im-new-group"');
    expect(page.text).toContain("feature=global-im-v73");
    expect(page.text).toContain("feature=im-narration-contrast-v1");
    expect(page.text).toContain("feature=im-member-add-plus-v2");
    expect(page.text).toContain("feature=im-button-hierarchy-v1");
    expect(page.text).toContain("feature=im-settings-gear-v1");
    expect(page.text).toContain("feature=im-icon-button-size-v1");
    expect(page.text).toContain("feature=im-sidebar-compact-v1");
    expect(application.text).toContain('/im.js?v=20260902-global-im-v73');
    expect(application.text).toContain("onRouteChange: schedulePresenceHeartbeat");
    expect(application.text).toContain("进入 IM 将放弃本地修改");
    expect(im.text).toContain("!await beforeOpen()");
    expect(application.text).toContain('if (imWorkspace.opened) return { view: "im" }');
    expect(application.text).toContain('if (context.view === "im") return imWorkspace.open()');
    expect(application.text).toContain('? "返回 IM"');
    expect(application.text).toContain('route.view === "im"');
    expect(application.text).toContain("imWorkspace.start();");
    expect(application.text).toContain("imWorkspace.activate()");
    expect(im.text).toContain('mentionMenu.addEventListener("pointerdown", (event) => event.preventDefault())');
    expect(application.text).toContain('if (!$("#im-view").classList.contains("hidden")) return { view: "im" }');
    expect(im.text).toContain("mention://${item.kind}/${item.id}");
    expect(im.text).toContain("const mentionPattern = /mention:");
    expect(im.text).toContain("(character|user)");
    expect(im.text).toContain('replyMode: String(form.get("replyMode") || "mention")');
    expect(im.text).toContain('api("/api/im/works")');
    expect(im.text).toContain('characterIds.length === 1');
    expect(im.text).toContain('submit.textContent = !hasWork ? "请先选择书籍" : count === 0 ? "请选择角色" : count === 1 ? "创建单聊"');
    expect(im.text).toContain("item.isPinned");
    expect(im.text).toContain("item.isFavorite");
    expect(im.text).toContain("data-im-remove-selected");
    expect(im.text).toContain('model.type === "announcement"');
    expect(im.text).toContain("/announcements");
    expect(im.text).toContain('toast("旁白公告已发布", "success")');
    expect(im.text).toContain("imAvatarHtml");
    expect(im.text).toContain("conversationAvatarHtml");
    expect(im.text).toContain("im-group-avatar-grid");
    expect(im.text).toContain('data-grid-size="${gridSize}"');
    expect(im.text).toContain("im-message-avatar");
    expect(im.text).toContain("im-member-avatar");
    expect(im.text).toContain("im-mention-avatar");
    expect(im.text).toContain("当前模型暂不可用");
    expect(im.text).toContain("data-im-open-member-add");
    expect(im.text).toContain("im-member-section-heading");
    expect(im.text).toContain("openMemberAddDialog");
    expect(im.text).toContain("loadMemberAddCharacters");
    expect(im.text).toContain("loadMemberAddHumans");
    expect(im.text).toContain('data-im-toggle-member-edit="${kind}"');
    expect(im.text).toContain('aria-pressed="false"');
    expect(im.text).toContain('data-im-remove-human="${esc(item.userId)}" aria-label="移除 ${esc(item.displayName)}" hidden');
    expect(im.text).toContain('data-im-remove-character="${esc(item.characterId)}" aria-label="移除 ${esc(item.name)}" hidden');
    expect(im.text).toContain("confirmToast(");
    expect(im.text).toContain('item.kind === "user" ? item.username : ""');
    expect(im.text).toContain('composer.setAttribute("aria-activedescendant", active.id)');
    expect(im.text).toContain('active.scrollIntoView({ block: "nearest" })');
    expect(im.text).toContain("if (bound) return;");
    expect(im.text).toContain("async function performMutation(control, action)");
    expect(im.text).toContain('control.setAttribute("aria-busy", "true")');
    expect(im.text).toContain("loadMoreConversations");
    expect(im.text).toContain("data-im-load-more-conversations");
    expect(im.text).toContain('api("/api/im/unread")');
    expect(im.text).toContain("conversationPageLoading");
    expect(page.text).toContain('id="im-create-human-search"');
    expect(page.text).toContain('role="textbox" aria-label="IM 消息"');
    expect(im.text).toContain("loadCreateHumans");
    expect(im.text).toContain("createSelectedHumans");
    expect(im.text).not.toContain('api("/api/users/directory?q=")');
    expect(im.text).toContain("const request = ++unreadRequest");
    expect(im.text).toContain("conversations.push(current)");
    expect(im.text).toContain("const unreadGeneration = ++unreadRequest");
    expect(im.text).toContain("if (!committed) {");
    expect(im.text).toContain("async function refreshAfterMutation(label, action)");
    expect(im.text).toContain("ownerConfirmationPending");
    expect(im.text).toContain("conversationDrafts");
    expect((im.text.match(/current\.id !== conversationId/gu) ?? []).length).toBeGreaterThanOrEqual(2);
    expect(im.text).toContain("pendingMessageRequests.get(conversationId)");
    expect(im.text).toContain("pendingAnnouncementRequests.get(conversationId)");
    expect(im.text).toContain("sendingConversations.has(conversationId)");
    expect(im.text).toContain("const savedDraft = conversationDrafts.get(conversationId)");
    expect(im.text).toContain("const submittedHtml = composer.innerHTML");
    expect(im.text).toContain("composer.innerHTML = newerDraftHtml");
    expect(im.text).toContain("void refreshUnreadTotal().catch(() => undefined)");
    expect(page.text).toContain('id="im-details-toggle"');
    expect(page.text).toContain('aria-expanded="false" disabled>成员与设置');
    expect(styles.text).toContain("#im-details-toggle, #im-details-close { display: none; }");
    expect(styles.text).toContain("#im-details-toggle { display: inline-flex; }");
    expect(styles.text).toContain(".im-group-form fieldset > label");
    expect(styles.text).toContain("min-height: 0; overflow: hidden; background: var(--paper)");
    expect(im.text).toContain('title: "转让群主", confirmLabel: "确认转让"');
    expect(im.text).toContain('title: "解散群聊", confirmLabel: "确认解散"');
    expect((im.text.match(/const conversationId = current\.id;/gu) ?? []).length).toBeGreaterThanOrEqual(2);
    expect(im.text).toContain('encodeURIComponent(conversationId)}/transfer');
    expect(im.text).toContain('encodeURIComponent(conversationId)}/disband');
    expect(im.text).not.toContain("loadConversations()");
    expect(im.text).not.toContain("window.confirm(");
    expect(im.text).toContain('class="im-owner-action-buttons"');
    expect(im.text.indexOf("主动判断诊断")).toBeLessThan(im.text.indexOf('class="im-owner-actions"'));
    expect(im.text).not.toContain('id="im-add-character-select"');
    expect(im.text).not.toContain('id="im-add-human-select"');
    expect(im.text).toContain('document.querySelector("#im-detail-threshold")');
    expect(im.text).toContain("serializeImComposer");
    expect(im.text).toContain("normalizeImComposerHeight");
    expect(im.text).toContain("normalizeImConversationWidth");
    expect(im.text).toContain("resolveImConversationWidth");
    expect(im.text).toContain("preferredConversationsWidth");
    expect(im.text).toContain("shouldMarkImConversationRead");
    expect(im.text).toContain("shouldRefreshImConversationListForEvent");
    expect(im.text).toContain("if (!opened)");
    expect(im.text).toContain("refreshConversations(),");
    expect(im.text).toContain("opened && current ? openConversation(current.id) : Promise.resolve()");
    expect(im.text).toContain('document.addEventListener("visibilitychange"');
    expect(im.text).toContain("setupConversationsResize");
    expect(im.text).toContain("let conversationRequest = 0");
    expect(im.text).toContain("let requestedConversationId = null");
    expect(im.text).toContain("let diagnosticsRequest = 0");
    expect(im.text).toContain("request !== diagnosticsRequest || current?.id !== conversationId");
    expect(im.text).toContain("requestedConversationId && requestedConversationId !== conversationId");
    expect(im.text).toContain("openConversation(button.dataset.imConversation, true)");
    expect(im.text).toContain("if (request !== conversationRequest) return");
    expect(im.text).toContain('conversationsResize.addEventListener("pointermove"');
    expect(im.text).toContain('conversationsWidth <= 180');
    expect(im.text).toContain('localStorage.setItem(conversationsWidthStorageKey');
    expect(im.text).toContain("setupComposerResize");
    expect(im.text).toContain('composerResize.addEventListener("pointermove"');
    expect(im.text).toContain('["ArrowUp", "ArrowDown", "Home", "End"]');
    expect(im.text).toContain("const provisionalReplies = new Map()");
    expect(im.text).toContain("syncProvisionalReplies");
    expect(im.text).toContain("upsertProvisionalReply");
    expect(im.text).toContain("updateProvisionalReplyElement");
    expect(im.text).toContain("feed.scrollHeight - feed.scrollTop - feed.clientHeight < 80");
    expect(im.text).toContain('article.querySelector(".im-message-body").innerHTML');
    expect(im.text).toContain('payload?.content !== undefined ? String(payload.content)');
    expect(im.text).toContain("个角色正在生成回答");
    expect(im.text).toContain('data-im-provisional-turn="${esc(reply.turnId)}"');
    expect(im.text).toContain('data-im-provisional-status="${esc(reply.status)}"');
    expect(im.text).toContain("角色回答生成失败");
    expect(styles.text).toContain(".im-view { display: grid; grid-template-columns:");
    expect(styles.text).toContain("var(--im-conversations-width, 300px)");
    expect(styles.text).toContain(".im-conversations-resize-handle { position: absolute;");
    expect(styles.text).toContain(".im-conversations.is-compact .im-new-conversation-compact { display: block;");
    expect(styles.text).toContain(".im-conversations.is-compact .im-conversation-item > span:nth-child(2) { display: none;");
    expect(styles.text).toContain("@media (max-width: 620px)");
    expect(styles.text).toContain(".im-composer-mention");
    expect(styles.text).toContain(".im-generating-summary");
    expect(styles.text).toContain(".im-provisional-error");
    expect(styles.text).toContain(".im-message.is-provisional.is-failed .im-message-body");
    expect(styles.text).toContain(".im-composer { height: 68px; min-height: 64px;");
    expect(styles.text).toContain(".im-composer-resize-handle { position: absolute;");
    expect(styles.text).toContain("body.is-im-composer-resizing");
    expect(styles.text).toContain(".im-send-button { position: absolute;");
    expect(styles.text).toContain("right: 26px; bottom: 25px;");
    expect(styles.text).toContain("right: 19px; bottom: 18px;");
    expect(styles.text).toContain(".im-send-button svg { width: 12px; height: 12px;");
    expect(styles.text).toContain(".im-button-secondary");
    expect(styles.text).toContain(".im-button-positive");
    expect(styles.text).toContain(".im-button-danger-quiet");
    expect(styles.text).toContain(".im-button:disabled");
    expect(styles.text).toContain(".im-button-announcement");
    expect(styles.text).toContain(".im-message.is-announcement");
    expect(styles.text).toContain(".im-announcement-form");
    expect(styles.text).toContain(".im-create-role-toolbar");
    expect(styles.text).toContain(".im-create-selected button");
    expect(styles.text).toContain(".im-character-preference.is-pinned");
    expect(styles.text).toContain('.im-option-grid input[type="checkbox"]');
    expect(styles.text).toContain("#im-details-content :is(input:not");
    expect(styles.text).toContain("#im-detail-threshold::-webkit-slider-thumb");
    expect(styles.text).toContain(".im-settings-dialog .account-settings-form");
    expect(styles.text).toContain(".im-conversation-single-avatar");
    expect(styles.text).toContain('.im-group-avatar-grid[data-grid-size="4"]');
    expect(styles.text).toContain('.im-group-avatar-grid[data-grid-size="9"]');
    expect(styles.text).toContain(".im-group-avatar-empty");
    expect(styles.text).toContain(".im-option-avatar");
    expect(styles.text).toContain(".im-selected-avatar");
    expect(styles.text).toContain(".im-message-avatar");
    expect(styles.text).toContain(".im-member-avatar");
    expect(styles.text).toContain(".im-member-add-button");
    expect(styles.text).toContain(".im-member-section-heading");
    expect(styles.text).toContain(".im-member-section-actions");
    expect(styles.text).toContain('.im-member-edit-button[aria-pressed="true"]');
    expect(styles.text).toContain(".im-member-add-dialog");
    expect(styles.text).toContain(".im-member-picker-option");
    expect(styles.text).toContain(".im-chat-header .im-button { min-height: 28px;");
    expect(styles.text).toContain(".im-owner-action-buttons { display: grid; grid-template-columns: repeat(2");
    expect(styles.text).toContain(".im-conversations { position: relative; display: flex; flex-direction: column;");
    expect(styles.text).toContain(".im-create-action-buttons");
    expect(styles.text).toContain(".im-button-secondary { border: 1px solid var(--line); background: var(--surface); color: var(--muted);");
    expect(styles.text).toContain(".im-button-announcement { border: 1px solid var(--im-narration-line); background: var(--im-narration-surface);");
    expect(styles.text).toContain("border: 1px solid color-mix(in srgb, var(--green) 58%, var(--line));");
    expect(styles.text).toContain("--im-narration-surface:");
    expect(styles.text).toContain("background: var(--im-narration-surface)");
    expect(styles.text).toContain("border-width: 1px 0");
  });
});
